--
-- PostgreSQL database dump
--

\restrict nOoLkPEeOl0vpEasa2IA4N2bgeTYeV0TiJ3defnDnm0vnbJFO6KJE9nDVDAyHr9

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


--
-- Name: generate_user_code(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.generate_user_code() RETURNS text
    LANGUAGE plpgsql
    AS $$
DECLARE
    seq_num INT;
BEGIN
    seq_num := nextval('user_code_seq');
    RETURN 'MHN' || LPAD(seq_num::TEXT, 6, '0');
END;
$$;


ALTER FUNCTION public.generate_user_code() OWNER TO postgres;

--
-- Name: set_user_code(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.set_user_code() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF NEW."UserCode" IS NULL THEN
        NEW."UserCode" := generate_user_code();
    END IF;
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.set_user_code() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Attachments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Attachments" (
    "Id" bigint NOT NULL,
    "OwnerType" text NOT NULL,
    "OwnerId" bigint NOT NULL,
    "S3Key" text NOT NULL,
    "Filename" text,
    "ContentType" text,
    "SizeBytes" bigint,
    "UploadedBy" uuid,
    "UploadedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Attachments" OWNER TO postgres;

--
-- Name: Attachments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Attachments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Attachments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AttendanceRecords; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AttendanceRecords" (
    "Id" integer NOT NULL,
    "UserId" character varying(128) NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Status" character varying(64) NOT NULL
);


ALTER TABLE public."AttendanceRecords" OWNER TO postgres;

--
-- Name: AttendanceRecords_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AttendanceRecords" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AttendanceRecords_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AuditLogs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AuditLogs" (
    "Id" bigint NOT NULL,
    "ActorId" uuid,
    "Action" text NOT NULL,
    "EntityType" text,
    "EntityId" text,
    "Details" text,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."AuditLogs" OWNER TO postgres;

--
-- Name: AuditLogs_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AuditLogs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AuditLogs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Meetings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Meetings" (
    "Id" bigint NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "Location" text,
    "LocationLat" numeric,
    "LocationLng" numeric,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone,
    "RsvpRequired" boolean NOT NULL
);


ALTER TABLE public."Meetings" OWNER TO postgres;

--
-- Name: Meetings_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Meetings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Meetings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Sermons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sermons" (
    "Id" bigint NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "S3Key" text NOT NULL,
    "DurationSeconds" integer,
    "Speaker" text,
    "PublishedAt" timestamp with time zone NOT NULL,
    "YoutubeUrl" text
);


ALTER TABLE public."Sermons" OWNER TO postgres;

--
-- Name: Sermons_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Sermons" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sermons_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tasks" (
    "Id" bigint NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "CreatedById" uuid,
    "AssigneeId" uuid,
    "TeamId" bigint,
    "Status" integer NOT NULL,
    "Priority" integer NOT NULL,
    "DueDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ClosedAt" timestamp with time zone
);


ALTER TABLE public."Tasks" OWNER TO postgres;

--
-- Name: Tasks_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tasks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tasks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Teams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Teams" (
    "Id" bigint NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "LeadUserId" uuid,
    "CreatedAt" timestamp with time zone DEFAULT now(),
    "UpdatedAt" timestamp with time zone DEFAULT now()
);


ALTER TABLE public."Teams" OWNER TO postgres;

--
-- Name: Teams_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Teams" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Teams_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Timesheets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Timesheets" (
    "Id" integer NOT NULL,
    "UserId" character varying(128) NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Hours" numeric NOT NULL,
    "Task" character varying(512),
    "Notes" character varying(2048)
);


ALTER TABLE public."Timesheets" OWNER TO postgres;

--
-- Name: Timesheets_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Timesheets" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Timesheets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "UserCode" character varying(16) NOT NULL,
    cognitosub text,
    username text,
    email text,
    phone text,
    displayname text,
    role text DEFAULT 'Member'::text NOT NULL,
    joindate timestamp with time zone DEFAULT now() NOT NULL,
    lastlogin timestamp with time zone,
    "MaritalStatus" text,
    "Sex" text,
    "IsBaptized" boolean,
    "BaptismPlace" text,
    "BaptismDate" timestamp with time zone,
    "IsBornAgain" boolean,
    "IsBeliever" boolean,
    "Birthday" timestamp with time zone,
    "Age" integer,
    "AadharNumber" text,
    "HomeAddress" text,
    "CurrentAddress" text,
    "EmergencyContactPhone" text,
    "IsPastor" boolean,
    passwordhash text
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: Users; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public."Users" AS
 SELECT id,
    "UserCode",
    cognitosub,
    username,
    email,
    phone,
    displayname,
    role,
    joindate,
    lastlogin,
    "MaritalStatus",
    "Sex",
    "IsBaptized",
    "BaptismPlace",
    "BaptismDate",
    "IsBornAgain",
    "IsBeliever",
    "Birthday",
    "Age",
    "AadharNumber",
    "HomeAddress",
    "CurrentAddress",
    "EmergencyContactPhone",
    "IsPastor"
   FROM public.users;


ALTER VIEW public."Users" OWNER TO postgres;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    type character varying(50) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: adminnotifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.adminnotifications (
    id bigint NOT NULL,
    userid uuid,
    type character varying(200) NOT NULL,
    message text,
    data text,
    isread boolean DEFAULT false NOT NULL,
    createdat timestamp with time zone NOT NULL
);


ALTER TABLE public.adminnotifications OWNER TO postgres;

--
-- Name: adminnotifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.adminnotifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.adminnotifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analytics_prayer_overview; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.analytics_prayer_overview (
    id integer NOT NULL,
    snapshot_at timestamp with time zone NOT NULL,
    period_label text NOT NULL,
    total_requests integer NOT NULL,
    open_requests integer NOT NULL,
    closed_requests integer NOT NULL,
    testified_requests integer NOT NULL
);


ALTER TABLE public.analytics_prayer_overview OWNER TO postgres;

--
-- Name: analytics_prayer_overview_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.analytics_prayer_overview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analytics_prayer_overview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analytics_task_by_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.analytics_task_by_role (
    id integer NOT NULL,
    role text NOT NULL,
    snapshot_at timestamp with time zone NOT NULL,
    total_tasks integer NOT NULL,
    completed_tasks integer NOT NULL,
    open_tasks integer NOT NULL,
    overdue_tasks integer NOT NULL
);


ALTER TABLE public.analytics_task_by_role OWNER TO postgres;

--
-- Name: analytics_task_by_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.analytics_task_by_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analytics_task_by_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analytics_team_productivity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.analytics_team_productivity (
    id integer NOT NULL,
    snapshot_at timestamp with time zone NOT NULL,
    team_id bigint NOT NULL,
    period_label text NOT NULL,
    period_start timestamp with time zone NOT NULL,
    period_end timestamp with time zone NOT NULL,
    total_hours double precision NOT NULL,
    avg_hours_per_user double precision NOT NULL
);


ALTER TABLE public.analytics_team_productivity OWNER TO postgres;

--
-- Name: analytics_team_productivity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.analytics_team_productivity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analytics_team_productivity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analytics_user_overview; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.analytics_user_overview (
    id integer NOT NULL,
    snapshot_at timestamp with time zone NOT NULL,
    total_users integer NOT NULL,
    total_admins integer NOT NULL,
    total_members integer NOT NULL,
    total_staff integer NOT NULL,
    total_volunteers integer NOT NULL,
    new_members_30d integer NOT NULL
);


ALTER TABLE public.analytics_user_overview OWNER TO postgres;

--
-- Name: analytics_user_overview_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.analytics_user_overview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analytics_user_overview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: baptism_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.baptism_requests (
    id integer NOT NULL,
    token text,
    full_name text NOT NULL,
    father_name text,
    mother_name text,
    date_of_birth timestamp with time zone,
    contact_number text,
    email text,
    address text,
    church_member_id integer,
    preferred_date timestamp with time zone,
    preferred_service text,
    church_verified boolean NOT NULL,
    church_verified_by integer,
    church_verified_at timestamp with time zone,
    consent_signed boolean NOT NULL,
    consent_signed_at timestamp with time zone,
    consent_signed_by integer,
    status text DEFAULT 'Pending'::text NOT NULL,
    certificate_pdf_url text,
    baptism_date timestamp with time zone,
    baptism_place text,
    baptized_by_user_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.baptism_requests OWNER TO postgres;

--
-- Name: baptism_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.baptism_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.baptism_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: candidates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.candidates (
    id uuid NOT NULL,
    full_name character varying(150) NOT NULL,
    email character varying(200),
    phone character varying(20) NOT NULL,
    is_church_member boolean NOT NULL,
    member_id text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.candidates OWNER TO postgres;

--
-- Name: chatmembers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chatmembers (
    chatid uuid NOT NULL,
    userid uuid NOT NULL,
    role character varying(50) NOT NULL,
    joinedat timestamp with time zone NOT NULL
);


ALTER TABLE public.chatmembers OWNER TO postgres;

--
-- Name: chats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chats (
    id uuid NOT NULL,
    name text,
    isgroup boolean NOT NULL,
    createdby uuid NOT NULL,
    createdat timestamp with time zone NOT NULL
);


ALTER TABLE public.chats OWNER TO postgres;

--
-- Name: counselling_cases; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.counselling_cases (
    id uuid NOT NULL,
    candidate_id uuid NOT NULL,
    issue_category character varying(100) NOT NULL,
    description text,
    status character varying(30) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    closed_at timestamp with time zone,
    last_updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.counselling_cases OWNER TO postgres;

--
-- Name: counselling_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.counselling_sessions (
    id uuid NOT NULL,
    case_id uuid NOT NULL,
    session_type character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    scheduled_at timestamp with time zone,
    location character varying(150),
    counselor_id uuid,
    token_number character varying(50),
    token_pdf_url text,
    outcome character varying(40) NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone
);


ALTER TABLE public.counselling_sessions OWNER TO postgres;

--
-- Name: expenses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.expenses (
    id bigint NOT NULL,
    description text NOT NULL,
    category character varying(64) NOT NULL,
    amount numeric(12,2) NOT NULL,
    date date NOT NULL,
    vendor text,
    notes text,
    payroll_person text,
    payroll_month character varying(7),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by_user_id bigint
);


ALTER TABLE public.expenses OWNER TO postgres;

--
-- Name: expenses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: journal_entries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.journal_entries (
    id bigint NOT NULL,
    date timestamp with time zone NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.journal_entries OWNER TO postgres;

--
-- Name: journal_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.journal_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.journal_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: journal_lines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.journal_lines (
    id bigint NOT NULL,
    journal_entry_id bigint NOT NULL,
    account_id bigint NOT NULL,
    debit numeric(12,2) NOT NULL,
    credit numeric(12,2) NOT NULL
);


ALTER TABLE public.journal_lines OWNER TO postgres;

--
-- Name: journal_lines_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.journal_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.journal_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: marriage_applications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marriage_applications (
    id uuid NOT NULL,
    groom_full_name character varying(200) NOT NULL,
    bride_full_name character varying(200) NOT NULL,
    groom_phone character varying(32),
    bride_phone character varying(32),
    groom_email character varying(256),
    bride_email character varying(256),
    address text,
    groom_is_member boolean NOT NULL,
    bride_is_member boolean NOT NULL,
    groom_member_id character varying(64),
    bride_member_id character varying(64),
    preferred_date timestamp with time zone,
    preferred_service character varying(64),
    scheduled_at timestamp with time zone,
    ceremony_location character varying(256),
    status character varying(64) NOT NULL,
    token character varying(50),
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    approved_at timestamp with time zone,
    approved_by_user_id character varying(128),
    completed_at timestamp with time zone
);


ALTER TABLE public.marriage_applications OWNER TO postgres;

--
-- Name: messagereads; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messagereads (
    messageid uuid NOT NULL,
    userid uuid NOT NULL,
    readat timestamp with time zone NOT NULL
);


ALTER TABLE public.messagereads OWNER TO postgres;

--
-- Name: messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messages (
    id uuid NOT NULL,
    chatid uuid NOT NULL,
    senderid uuid NOT NULL,
    content text,
    contenttype text NOT NULL,
    attachmenturl text,
    createdat timestamp with time zone NOT NULL
);


ALTER TABLE public.messages OWNER TO postgres;

--
-- Name: pages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pages (
    key character varying(200) NOT NULL,
    id integer,
    title text,
    description text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);


ALTER TABLE public.pages OWNER TO postgres;

--
-- Name: payroll_runs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payroll_runs (
    id uuid NOT NULL,
    user_id character varying(128) NOT NULL,
    staff_name character varying(256),
    from_date timestamp with time zone NOT NULL,
    to_date timestamp with time zone NOT NULL,
    total_hours numeric(18,2) NOT NULL,
    hourly_rate numeric(18,2) NOT NULL,
    fixed_amount numeric(18,2) NOT NULL,
    allowances numeric(18,2) NOT NULL,
    deductions numeric(18,2) NOT NULL,
    gross_amount numeric(18,2) NOT NULL,
    net_amount numeric(18,2) NOT NULL,
    run_at timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public.payroll_runs OWNER TO postgres;

--
-- Name: prayerrequests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prayerrequests (
    id bigint NOT NULL,
    userid uuid,
    title character varying(500),
    message text,
    anonymous boolean NOT NULL,
    status character varying(50) NOT NULL,
    assignedto uuid,
    createdat timestamp with time zone NOT NULL,
    createdby character varying(200),
    closecomment text
);


ALTER TABLE public.prayerrequests OWNER TO postgres;

--
-- Name: prayerrequests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prayerrequests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prayerrequests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prayerresponses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prayerresponses (
    id bigint NOT NULL,
    prayerrequestid bigint NOT NULL,
    userid uuid,
    message text NOT NULL,
    author character varying(200),
    createdat timestamp with time zone NOT NULL,
    updatedat timestamp with time zone
);


ALTER TABLE public.prayerresponses OWNER TO postgres;

--
-- Name: prayerresponses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prayerresponses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prayerresponses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_permissions (
    id integer NOT NULL,
    role_id integer NOT NULL,
    page_key text NOT NULL
);


ALTER TABLE public.role_permissions OWNER TO postgres;

--
-- Name: role_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: staff_payroll_settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.staff_payroll_settings (
    id integer NOT NULL,
    user_id character varying(128) NOT NULL,
    hourly_rate numeric(18,2) NOT NULL,
    monthly_fixed_amount numeric(18,2),
    allowances numeric(18,2),
    deductions numeric(18,2),
    is_active boolean DEFAULT true NOT NULL,
    "ExpectedMonthlyHours" numeric DEFAULT 0.0 NOT NULL,
    "SalaryType" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public.staff_payroll_settings OWNER TO postgres;

--
-- Name: staff_payroll_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.staff_payroll_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.staff_payroll_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teammembers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teammembers (
    teamid bigint NOT NULL,
    userid uuid NOT NULL,
    "RoleInTeam" text,
    "JoinedAt" timestamp with time zone NOT NULL,
    "IsLeader" boolean DEFAULT false
);


ALTER TABLE public.teammembers OWNER TO postgres;

--
-- Name: user_code_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_code_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_code_seq OWNER TO postgres;

--
-- Data for Name: Attachments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Attachments" ("Id", "OwnerType", "OwnerId", "S3Key", "Filename", "ContentType", "SizeBytes", "UploadedBy", "UploadedAt") FROM stdin;
\.


--
-- Data for Name: AttendanceRecords; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AttendanceRecords" ("Id", "UserId", "Date", "Status") FROM stdin;
24	b327b6fc-8104-4a04-a308-0a5172058511	2026-04-19 00:00:00	Present
25	b327b6fc-8104-4a04-a308-0a5172058511	2026-04-20 00:00:00	Present
26	b327b6fc-8104-4a04-a308-0a5172058511	2026-04-18 00:00:00	Present
27	55f32493-dd32-4230-a2fe-cf23e7801926	2026-04-20 00:00:00	Present
28	55f32493-dd32-4230-a2fe-cf23e7801926	2026-04-19 00:00:00	Present
\.


--
-- Data for Name: AuditLogs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AuditLogs" ("Id", "ActorId", "Action", "EntityType", "EntityId", "Details", "CreatedAt") FROM stdin;
19	b48e8afc-05fb-4121-aada-97ac24bce54e	Attendance.Create	AttendanceRecord	9	{"Id":9,"UserId":"b48e8afc-05fb-4121-aada-97ac24bce54e","Date":"2026-04-16T00:00:00","Status":"Present"}	2026-04-16 12:34:51.005182+00
20	b48e8afc-05fb-4121-aada-97ac24bce54e	Attendance.Delete	AttendanceRecord	9	{"UserId":"b48e8afc-05fb-4121-aada-97ac24bce54e","Date":"2026-04-16T00:00:00","Status":"Present"}	2026-04-16 12:41:16.405615+00
21	b48e8afc-05fb-4121-aada-97ac24bce54e	Attendance.Create	AttendanceRecord	10	{"Id":10,"UserId":"b48e8afc-05fb-4121-aada-97ac24bce54e","Date":"2026-04-16T00:00:00","Status":"Present"}	2026-04-16 12:41:26.025608+00
22	e46ddcfb-ebc2-49bd-8260-b1c6c4d3f036	Attendance.Create	AttendanceRecord	11	{"Id":11,"UserId":"e46ddcfb-ebc2-49bd-8260-b1c6c4d3f036","Date":"2026-04-15T00:00:00","Status":"Present"}	2026-04-16 12:42:19.174343+00
23	3e09c1e3-96ea-4c66-b765-1ec3266e6236	Attendance.Create	AttendanceRecord	13	{"Id":13,"UserId":"96e254e4-2767-4c7a-913a-803a5e9b4380","Date":"2026-04-16T00:00:00","Status":"Present"}	2026-04-16 14:05:41.530686+00
24	3e09c1e3-96ea-4c66-b765-1ec3266e6236	Timesheet.Create	Timesheet	5	{"Id":5,"UserId":"96e254e4-2767-4c7a-913a-803a5e9b4380","Date":"2026-04-16T00:00:00","Hours":3,"Task":"sasa","Notes":""}	2026-04-16 14:05:55.427693+00
25	a9307304-568a-441c-b72c-3e7b729996ad	Attendance.Create	AttendanceRecord	14	{"Id":14,"UserId":"a9307304-568a-441c-b72c-3e7b729996ad","Date":"2026-04-16T14:06:11.71","Status":"Present"}	2026-04-16 14:11:32.885917+00
26	a9307304-568a-441c-b72c-3e7b729996ad	Attendance.Create	AttendanceRecord	15	{"Id":15,"UserId":"a9307304-568a-441c-b72c-3e7b729996ad","Date":"2026-04-16T14:07:47.636","Status":"Present"}	2026-04-16 14:13:08.809874+00
27	a9307304-568a-441c-b72c-3e7b729996ad	Attendance.Delete	AttendanceRecord	14	{"UserId":"a9307304-568a-441c-b72c-3e7b729996ad","Date":"2026-04-16T14:06:11.71","Status":"Present"}	2026-04-16 14:20:51.200794+00
28	a9307304-568a-441c-b72c-3e7b729996ad	Attendance.Delete	AttendanceRecord	15	{"UserId":"a9307304-568a-441c-b72c-3e7b729996ad","Date":"2026-04-16T14:07:47.636","Status":"Present"}	2026-04-16 14:20:56.370999+00
29	a9307304-568a-441c-b72c-3e7b729996ad	Attendance.Create	AttendanceRecord	16	{"Id":16,"UserId":"a9307304-568a-441c-b72c-3e7b729996ad","Date":"2026-04-16T14:15:36.64","Status":"Present"}	2026-04-16 14:20:57.807693+00
30	a9307304-568a-441c-b72c-3e7b729996ad	Attendance.Delete	AttendanceRecord	16	{"UserId":"a9307304-568a-441c-b72c-3e7b729996ad","Date":"2026-04-16T14:15:36.64","Status":"Present"}	2026-04-16 14:21:02.211584+00
31	8b4bc074-b554-4b9a-ad55-94947341f1b0	Attendance.Create	AttendanceRecord	17	{"Id":17,"UserId":"8b4bc074-b554-4b9a-ad55-94947341f1b0","Date":"2026-04-16T14:16:01.777","Status":"Present"}	2026-04-16 14:21:22.944566+00
32	8b4bc074-b554-4b9a-ad55-94947341f1b0	Attendance.Create	AttendanceRecord	18	{"Id":18,"UserId":"8b4bc074-b554-4b9a-ad55-94947341f1b0","Date":"2026-04-16T14:20:41.408","Status":"Present"}	2026-04-16 14:26:02.990895+00
33	8b4bc074-b554-4b9a-ad55-94947341f1b0	Attendance.Delete	AttendanceRecord	17	{"UserId":"8b4bc074-b554-4b9a-ad55-94947341f1b0","Date":"2026-04-16T14:16:01.777","Status":"Present"}	2026-04-16 14:26:05.783041+00
34	8b4bc074-b554-4b9a-ad55-94947341f1b0	Attendance.Create	AttendanceRecord	19	{"Id":19,"UserId":"8b4bc074-b554-4b9a-ad55-94947341f1b0","Date":"2026-04-16T14:20:46.673","Status":"Absent"}	2026-04-16 14:26:07.842888+00
35	8b4bc074-b554-4b9a-ad55-94947341f1b0	Attendance.Delete	AttendanceRecord	19	{"UserId":"8b4bc074-b554-4b9a-ad55-94947341f1b0","Date":"2026-04-16T14:20:46.673","Status":"Absent"}	2026-04-16 14:26:09.413544+00
36	8b4bc074-b554-4b9a-ad55-94947341f1b0	Timesheet.Create	Timesheet	6	{"Id":6,"UserId":"8b4bc074-b554-4b9a-ad55-94947341f1b0","Date":"2026-04-16T00:00:00","Hours":3,"Task":"dsds","Notes":null}	2026-04-16 14:26:15.334865+00
37	11623916-904f-4a6b-a9fa-24b3ca8104c0	Attendance.Delete	AttendanceRecord	13	{"UserId":"96e254e4-2767-4c7a-913a-803a5e9b4380","Date":"2026-04-16T00:00:00","Status":"Present"}	2026-04-16 14:27:18.713294+00
38	165d058d-bda0-4a9c-926e-421f6f703f04	Attendance.Create	AttendanceRecord	20	{"Id":20,"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","Date":"2026-04-16T14:29:57.352","Status":"Present"}	2026-04-16 14:35:18.60429+00
39	96e254e4-2767-4c7a-913a-803a5e9b4380	Timesheet.Create	Timesheet	7	{"Id":7,"UserId":"96e254e4-2767-4c7a-913a-803a5e9b4380","Date":"2026-04-16T00:00:00","Hours":9,"Task":"Day Task","Notes":null}	2026-04-16 15:29:48.037182+00
40	\N	Payroll.Run.Create	PayrollRun	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":"07102632-80a2-4156-93f9-a4f13c4e4433","UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":9,"HourlyRate":0,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":0,"NetAmount":0,"RunAt":"0001-01-01T00:00:00"}	2026-04-16 15:31:30.332576+00
41	\N	Payroll.Settings.Create	StaffPayrollSetting	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":0,"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","HourlyRate":20,"MonthlyFixedAmount":0,"Allowances":0,"Deductions":0,"IsActive":true}	2026-04-16 15:31:44.853107+00
42	\N	Payroll.Run.Delete	PayrollRun	ec5a72b9-026d-4f76-9a5b-6c925f35e03d	{"UserId":"55f32493-dd32-4230-a2fe-cf23e7801926","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-16 15:31:53.073117+00
43	\N	Payroll.Run.Delete	PayrollRun	07102632-80a2-4156-93f9-a4f13c4e4433	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-16 15:31:55.064603+00
44	\N	Payroll.Run.Create	PayrollRun	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":"7fce2f1d-b925-4bae-b35b-9f07060f6351","UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":9,"HourlyRate":20,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":180,"NetAmount":180,"RunAt":"0001-01-01T00:00:00"}	2026-04-16 15:32:00.123739+00
45	165d058d-bda0-4a9c-926e-421f6f703f04	Attendance.Create	AttendanceRecord	22	{"Id":22,"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","Date":"2026-04-17T00:00:00","Status":"Present"}	2026-04-17 02:48:33.621915+00
46	165d058d-bda0-4a9c-926e-421f6f703f04	Timesheet.Create	Timesheet	8	{"Id":8,"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","Date":"2026-04-17T00:00:00","Hours":9,"Task":"","Notes":""}	2026-04-17 02:48:53.580762+00
47	\N	Payroll.Settings.Update	StaffPayrollSetting	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":0,"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","HourlyRate":400,"MonthlyFixedAmount":0,"Allowances":0,"Deductions":0,"IsActive":true}	2026-04-17 02:50:19.666049+00
48	\N	Payroll.Run.Delete	PayrollRun	7fce2f1d-b925-4bae-b35b-9f07060f6351	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-17 02:50:23.318783+00
49	\N	Payroll.Run.Create	PayrollRun	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":"05953234-8f50-4498-aed8-ab24805fd1fe","UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18,"HourlyRate":400,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":7200,"NetAmount":7200,"RunAt":"0001-01-01T00:00:00"}	2026-04-17 02:50:27.618688+00
50	\N	Payroll.Run.Delete	PayrollRun	05953234-8f50-4498-aed8-ab24805fd1fe	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-17 02:51:30.069929+00
51	\N	Payroll.Settings.Update	StaffPayrollSetting	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":0,"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","HourlyRate":37.03,"MonthlyFixedAmount":0,"Allowances":0,"Deductions":0,"IsActive":true}	2026-04-17 02:53:32.675255+00
52	\N	Payroll.Run.Create	PayrollRun	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":"70514a85-6cc8-45e9-9c48-419d7d7759c1","UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18,"HourlyRate":37.03,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54,"RunAt":"0001-01-01T00:00:00"}	2026-04-17 02:53:35.005418+00
53	\N	Payroll.Run.Slip	PayrollRun	70514a85-6cc8-45e9-9c48-419d7d7759c1	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","DisplayName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18.00,"HourlyRate":37.03,"FixedAmount":0,"HourlyAmount":666.5400,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54}	2026-04-17 03:09:51.08875+00
54	\N	Payroll.Run.Create	PayrollRun	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":"1591c854-169b-42e1-97af-79f61254aa0e","UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18,"HourlyRate":37.03,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54,"RunAt":"0001-01-01T00:00:00"}	2026-04-17 03:10:51.601531+00
55	\N	Payroll.Run.Create	PayrollRun	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":"c25491d6-ce7a-4f5f-8025-516469640170","UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18,"HourlyRate":37.03,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54,"RunAt":"0001-01-01T00:00:00"}	2026-04-17 03:14:58.298995+00
56	\N	Payroll.Run.Create	PayrollRun	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":"c0471b9c-0257-478b-90e3-37a7e116a24d","UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18,"HourlyRate":37.03,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54,"RunAt":"0001-01-01T00:00:00"}	2026-04-17 03:15:42.612504+00
57	\N	Payroll.Run.Delete	PayrollRun	c25491d6-ce7a-4f5f-8025-516469640170	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-17 08:33:44.199753+00
58	\N	Payroll.Run.Delete	PayrollRun	c0471b9c-0257-478b-90e3-37a7e116a24d	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-17 08:33:45.939875+00
59	\N	Payroll.Run.Delete	PayrollRun	70514a85-6cc8-45e9-9c48-419d7d7759c1	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-17 08:33:47.017349+00
60	\N	Payroll.Run.Delete	PayrollRun	1591c854-169b-42e1-97af-79f61254aa0e	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-17 08:33:48.9586+00
61	\N	Payroll.Run.Create	PayrollRun	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":"a1115024-52a7-4158-afc4-3a830a368f97","UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18,"HourlyRate":37.03,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54,"RunAt":"0001-01-01T00:00:00"}	2026-04-17 09:10:59.975548+00
62	\N	Payroll.Run.Slip	PayrollRun	a1115024-52a7-4158-afc4-3a830a368f97	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","DisplayName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18.00,"HourlyRate":37.03,"FixedAmount":0,"HourlyAmount":666.5400,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54}	2026-04-17 09:11:05.097919+00
63	\N	Payroll.Run.Create	PayrollRun	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":"3f41da74-33ca-415c-a443-42758c33d3e0","UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18,"HourlyRate":37.03,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54,"RunAt":"0001-01-01T00:00:00"}	2026-04-17 09:18:30.995302+00
91	96e254e4-2767-4c7a-913a-803a5e9b4380	Timesheet.Delete	Timesheet	7	{"UserId":"96e254e4-2767-4c7a-913a-803a5e9b4380","Date":"2026-04-16T00:00:00","Hours":9,"Task":"Day Task","Notes":null}	2026-04-20 17:12:47.437287+00
64	\N	Payroll.Run.Slip	PayrollRun	a1115024-52a7-4158-afc4-3a830a368f97	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","DisplayName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18.00,"HourlyRate":37.03,"FixedAmount":0,"HourlyAmount":666.5400,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54}	2026-04-17 09:27:27.189812+00
65	\N	Payroll.Run.Slip	PayrollRun	a1115024-52a7-4158-afc4-3a830a368f97	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","DisplayName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18.00,"HourlyRate":37.03,"FixedAmount":0,"HourlyAmount":666.5400,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54}	2026-04-17 09:51:34.21516+00
66	\N	Payroll.Run.Create	PayrollRun	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":"7837f0db-8e7b-4c1f-a890-48febc0da8b4","UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18,"HourlyRate":37.03,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54,"RunAt":"0001-01-01T00:00:00"}	2026-04-17 09:52:24.672079+00
67	\N	Payroll.Run.Delete	PayrollRun	7837f0db-8e7b-4c1f-a890-48febc0da8b4	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-17 09:52:29.807731+00
68	\N	Payroll.Run.Delete	PayrollRun	a1115024-52a7-4158-afc4-3a830a368f97	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-17 09:52:30.992464+00
69	\N	Payroll.Run.Delete	PayrollRun	3f41da74-33ca-415c-a443-42758c33d3e0	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-17 09:52:31.938441+00
70	\N	Payroll.Run.Create	PayrollRun	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":"4b84c52e-37a6-40ca-8e78-3b64291f4e6a","UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18,"HourlyRate":37.03,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54,"RunAt":"0001-01-01T00:00:00"}	2026-04-17 09:52:34.392654+00
71	\N	Payroll.Run.Slip	PayrollRun	4b84c52e-37a6-40ca-8e78-3b64291f4e6a	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","DisplayName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18.00,"HourlyRate":37.03,"FixedAmount":0,"HourlyAmount":666.5400,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54}	2026-04-17 09:52:36.943398+00
72	\N	Payroll.Run.Create	PayrollRun	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":"4526120d-91a5-4b3c-ab1d-bd839c6dc7e5","UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18,"HourlyRate":37.03,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54,"RunAt":"0001-01-01T00:00:00"}	2026-04-17 10:49:32.723048+00
73	\N	Payroll.Run.Delete	PayrollRun	4526120d-91a5-4b3c-ab1d-bd839c6dc7e5	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-17 10:49:39.139534+00
74	\N	Payroll.Run.Delete	PayrollRun	4b84c52e-37a6-40ca-8e78-3b64291f4e6a	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-17 10:49:40.138698+00
75	\N	Payroll.Run.Create	PayrollRun	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":"58963400-85c6-4a80-acba-086a7fa50c3b","UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18,"HourlyRate":37.03,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54,"RunAt":"0001-01-01T00:00:00"}	2026-04-17 10:49:43.066721+00
76	\N	Payroll.Run.Slip	PayrollRun	58963400-85c6-4a80-acba-086a7fa50c3b	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","DisplayName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18.00,"HourlyRate":37.03,"FixedAmount":0,"HourlyAmount":666.5400,"Allowances":0,"Deductions":0,"GrossAmount":666.54,"NetAmount":666.54}	2026-04-17 10:49:45.812538+00
77	96e254e4-2767-4c7a-913a-803a5e9b4380	Attendance.Create	AttendanceRecord	23	{"Id":23,"UserId":"91ac3e52-0966-4c72-8fa6-22c52afa5e80","Date":"2026-04-17T00:00:00","Status":"Absent"}	2026-04-17 11:39:41.175817+00
78	96e254e4-2767-4c7a-913a-803a5e9b4380	Timesheet.Create	Timesheet	9	{"Id":9,"UserId":"91ac3e52-0966-4c72-8fa6-22c52afa5e80","Date":"2026-04-17T00:00:00","Hours":9,"Task":"","Notes":""}	2026-04-17 11:40:03.078567+00
79	96e254e4-2767-4c7a-913a-803a5e9b4380	Attendance.Update	AttendanceRecord	23	{"before":{"UserId":"91ac3e52-0966-4c72-8fa6-22c52afa5e80","Date":"2026-04-17T00:00:00","Status":"Absent"},"after":{"UserId":"91ac3e52-0966-4c72-8fa6-22c52afa5e80","Date":"2026-04-17T00:00:00","Status":"Present"}}	2026-04-17 11:40:24.310735+00
80	\N	Payroll.Run.Delete	PayrollRun	58963400-85c6-4a80-acba-086a7fa50c3b	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-17 11:40:58.758751+00
81	\N	Payroll.Settings.Create	StaffPayrollSetting	91ac3e52-0966-4c72-8fa6-22c52afa5e80	{"Id":0,"UserId":"91ac3e52-0966-4c72-8fa6-22c52afa5e80","HourlyRate":11.11,"MonthlyFixedAmount":0,"Allowances":0,"Deductions":0,"IsActive":true}	2026-04-17 11:41:51.069185+00
82	\N	Payroll.Run.Create	PayrollRun	91ac3e52-0966-4c72-8fa6-22c52afa5e80	{"Id":"604fad21-2b20-47f9-886b-40737d284eac","UserId":"91ac3e52-0966-4c72-8fa6-22c52afa5e80","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":27,"HourlyRate":11.11,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":299.96999999999997,"NetAmount":299.96999999999997,"RunAt":"0001-01-01T00:00:00"}	2026-04-17 11:41:58.096886+00
83	\N	Payroll.Run.Create	PayrollRun	165d058d-bda0-4a9c-926e-421f6f703f04	{"Id":"6073b9f4-c00a-408a-9193-92257207f73f","UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":27,"HourlyRate":37.03,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":999.8100000000001,"NetAmount":999.8100000000001,"RunAt":"0001-01-01T00:00:00"}	2026-04-17 11:43:40.093097+00
84	96e254e4-2767-4c7a-913a-803a5e9b4380	Attendance.Create	AttendanceRecord	24	{"Id":24,"UserId":"b327b6fc-8104-4a04-a308-0a5172058511","Date":"2026-04-19T00:00:00","Status":"Present"}	2026-04-20 17:12:06.489172+00
85	96e254e4-2767-4c7a-913a-803a5e9b4380	Attendance.Create	AttendanceRecord	25	{"Id":25,"UserId":"b327b6fc-8104-4a04-a308-0a5172058511","Date":"2026-04-20T00:00:00","Status":"Present"}	2026-04-20 17:12:28.582034+00
86	96e254e4-2767-4c7a-913a-803a5e9b4380	Attendance.Delete	AttendanceRecord	22	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","Date":"2026-04-17T00:00:00","Status":"Present"}	2026-04-20 17:12:38.13418+00
87	96e254e4-2767-4c7a-913a-803a5e9b4380	Attendance.Delete	AttendanceRecord	23	{"UserId":"91ac3e52-0966-4c72-8fa6-22c52afa5e80","Date":"2026-04-17T00:00:00","Status":"Present"}	2026-04-20 17:12:39.398574+00
88	96e254e4-2767-4c7a-913a-803a5e9b4380	Attendance.Delete	AttendanceRecord	20	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","Date":"2026-04-16T14:29:57.352","Status":"Present"}	2026-04-20 17:12:40.369831+00
89	96e254e4-2767-4c7a-913a-803a5e9b4380	Timesheet.Delete	Timesheet	8	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","Date":"2026-04-17T00:00:00","Hours":9,"Task":"","Notes":""}	2026-04-20 17:12:45.690434+00
90	96e254e4-2767-4c7a-913a-803a5e9b4380	Timesheet.Delete	Timesheet	9	{"UserId":"91ac3e52-0966-4c72-8fa6-22c52afa5e80","Date":"2026-04-17T00:00:00","Hours":9,"Task":"","Notes":""}	2026-04-20 17:12:46.542809+00
92	b327b6fc-8104-4a04-a308-0a5172058511	Attendance.Create	AttendanceRecord	26	{"Id":26,"UserId":"b327b6fc-8104-4a04-a308-0a5172058511","Date":"2026-04-18T00:00:00","Status":"Present"}	2026-04-20 17:14:23.080089+00
93	55f32493-dd32-4230-a2fe-cf23e7801926	Attendance.Create	AttendanceRecord	27	{"Id":27,"UserId":"55f32493-dd32-4230-a2fe-cf23e7801926","Date":"2026-04-20T00:00:00","Status":"Present"}	2026-04-20 17:15:10.697828+00
94	55f32493-dd32-4230-a2fe-cf23e7801926	Attendance.Create	AttendanceRecord	28	{"Id":28,"UserId":"55f32493-dd32-4230-a2fe-cf23e7801926","Date":"2026-04-19T00:00:00","Status":"Present"}	2026-04-20 17:15:26.913494+00
95	\N	Payroll.Run.Delete	PayrollRun	6073b9f4-c00a-408a-9193-92257207f73f	{"UserId":"165d058d-bda0-4a9c-926e-421f6f703f04","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-20 17:15:56.124161+00
96	\N	Payroll.Run.Delete	PayrollRun	604fad21-2b20-47f9-886b-40737d284eac	{"UserId":"91ac3e52-0966-4c72-8fa6-22c52afa5e80","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-20 17:15:57.062375+00
97	\N	Payroll.Run.Create	PayrollRun	55f32493-dd32-4230-a2fe-cf23e7801926	{"Id":"597d494c-980c-4cac-bd4c-c2fddf1c84e1","UserId":"55f32493-dd32-4230-a2fe-cf23e7801926","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":45,"HourlyRate":0,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":0,"NetAmount":0,"RunAt":"0001-01-01T00:00:00"}	2026-04-20 17:15:59.023885+00
98	\N	Payroll.Run.Delete	PayrollRun	597d494c-980c-4cac-bd4c-c2fddf1c84e1	{"UserId":"55f32493-dd32-4230-a2fe-cf23e7801926","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-20 17:20:23.754899+00
99	\N	Payroll.Run.Create	PayrollRun	55f32493-dd32-4230-a2fe-cf23e7801926	{"Id":"21c96a56-4bdd-4fb6-bc8b-61eb2dc405d1","UserId":"55f32493-dd32-4230-a2fe-cf23e7801926","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":45,"HourlyRate":0,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":0,"NetAmount":0,"RunAt":"0001-01-01T00:00:00"}	2026-04-20 17:20:25.404118+00
100	\N	Payroll.Summary	Payroll	b327b6fc-8104-4a04-a308-0a5172058511	{"from":"2026-04-01T00:00:00","to":"2026-04-30T00:00:00","summary":{"UserId":"b327b6fc-8104-4a04-a308-0a5172058511","DisplayName":"b327b6fc-8104-4a04-a308-0a5172058511","From":"2026-04-01T00:00:00","To":"2026-04-30T00:00:00","TotalHours":0,"HourlyRate":18.51,"FixedAmount":5000.00,"HourlyAmount":0.00,"Allowances":0,"Deductions":0,"GrossAmount":0.00,"NetAmount":0.00}}	2026-04-21 08:12:32.317239+00
101	\N	Payroll.Run.Create	PayrollRun	b327b6fc-8104-4a04-a308-0a5172058511	{"Id":"bffa2775-0c43-4b35-b6c7-e75a4ff280c8","UserId":"b327b6fc-8104-4a04-a308-0a5172058511","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":27,"HourlyRate":18.51,"FixedAmount":5000,"Allowances":0,"Deductions":0,"GrossAmount":499.77000000000004,"NetAmount":499.77000000000004,"RunAt":"2026-04-21T08:12:32.450815Z","CreatedAt":"2026-04-21T08:12:32.4508151Z"}	2026-04-21 08:12:32.468267+00
102	\N	Payroll.Summary	Payroll	55f32493-dd32-4230-a2fe-cf23e7801926	{"from":"2026-04-01T00:00:00","to":"2026-04-30T00:00:00","summary":{"UserId":"55f32493-dd32-4230-a2fe-cf23e7801926","DisplayName":"55f32493-dd32-4230-a2fe-cf23e7801926","From":"2026-04-01T00:00:00","To":"2026-04-30T00:00:00","TotalHours":0,"HourlyRate":0,"FixedAmount":0,"HourlyAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":0,"NetAmount":0}}	2026-04-21 08:15:15.412917+00
103	\N	Payroll.Run.Create	PayrollRun	55f32493-dd32-4230-a2fe-cf23e7801926	{"Id":"b61f5d35-8ab6-424c-954e-0b0d925caddf","UserId":"55f32493-dd32-4230-a2fe-cf23e7801926","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18,"HourlyRate":0,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":0,"NetAmount":0,"RunAt":"2026-04-21T08:15:15.4949531Z","CreatedAt":"2026-04-21T08:15:15.4949531Z"}	2026-04-21 08:15:15.495522+00
104	\N	Payroll.Settings.Create	StaffPayrollSetting	55f32493-dd32-4230-a2fe-cf23e7801926	{"Id":0,"UserId":"55f32493-dd32-4230-a2fe-cf23e7801926","HourlyRate":20,"MonthlyFixedAmount":0,"Allowances":0,"Deductions":0,"IsActive":true,"ExpectedMonthlyHours":0,"SalaryType":"Fixed"}	2026-04-21 08:15:35.600277+00
105	\N	Payroll.Summary	Payroll	55f32493-dd32-4230-a2fe-cf23e7801926	{"from":"2026-04-01T00:00:00","to":"2026-04-30T00:00:00","summary":{"UserId":"55f32493-dd32-4230-a2fe-cf23e7801926","DisplayName":"55f32493-dd32-4230-a2fe-cf23e7801926","From":"2026-04-01T00:00:00","To":"2026-04-30T00:00:00","TotalHours":0,"HourlyRate":20.00,"FixedAmount":0,"HourlyAmount":0.00,"Allowances":0,"Deductions":0,"GrossAmount":0.00,"NetAmount":0.00}}	2026-04-21 08:15:40.224586+00
106	\N	Payroll.Run.Create	PayrollRun	55f32493-dd32-4230-a2fe-cf23e7801926	{"Id":"b50943ff-edca-47c7-b35b-6f1affb3c368","UserId":"55f32493-dd32-4230-a2fe-cf23e7801926","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":18,"HourlyRate":20,"FixedAmount":0,"Allowances":0,"Deductions":0,"GrossAmount":360,"NetAmount":360,"RunAt":"2026-04-21T08:15:40.2667303Z","CreatedAt":"2026-04-21T08:15:40.2667303Z"}	2026-04-21 08:15:40.267028+00
107	\N	Payroll.Run.Delete	PayrollRun	b61f5d35-8ab6-424c-954e-0b0d925caddf	{"UserId":"55f32493-dd32-4230-a2fe-cf23e7801926","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-21 08:15:47.606584+00
108	\N	Payroll.Run.Delete	PayrollRun	21c96a56-4bdd-4fb6-bc8b-61eb2dc405d1	{"UserId":"55f32493-dd32-4230-a2fe-cf23e7801926","From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z"}	2026-04-21 08:15:48.964833+00
109	\N	Payroll.Slip.Generate	Payroll	55f32493-dd32-4230-a2fe-cf23e7801926	{"from":"2026-04-01T00:00:00","to":"2026-04-30T00:00:00","summary":{"UserId":"55f32493-dd32-4230-a2fe-cf23e7801926","DisplayName":"55f32493-dd32-4230-a2fe-cf23e7801926","From":"2026-04-01T00:00:00","To":"2026-04-30T00:00:00","TotalHours":0,"HourlyRate":20.00,"FixedAmount":0,"HourlyAmount":0.00,"Allowances":0,"Deductions":0,"GrossAmount":0.00,"NetAmount":0.00}}	2026-04-21 08:15:53.770811+00
110	\N	Payroll.Summary	Payroll	b327b6fc-8104-4a04-a308-0a5172058511	{"from":"2026-04-01T00:00:00","to":"2026-04-30T00:00:00","summary":{"UserId":"b327b6fc-8104-4a04-a308-0a5172058511","DisplayName":"b327b6fc-8104-4a04-a308-0a5172058511","From":"2026-04-01T00:00:00","To":"2026-04-30T00:00:00","TotalHours":0,"HourlyRate":18.51,"FixedAmount":5000.00,"HourlyAmount":0.00,"Allowances":0,"Deductions":0,"GrossAmount":0.00,"NetAmount":0.00}}	2026-04-21 15:47:13.697734+00
111	\N	Payroll.Run.Create	PayrollRun	b327b6fc-8104-4a04-a308-0a5172058511	{"Id":"20f7e57f-e377-4e67-b571-85dd8bc61d2c","UserId":"b327b6fc-8104-4a04-a308-0a5172058511","StaffName":null,"From":"2026-04-01T00:00:00Z","To":"2026-04-30T00:00:00Z","TotalHours":27,"HourlyRate":18.51,"FixedAmount":5000,"Allowances":0,"Deductions":500,"GrossAmount":499.77000000000004,"NetAmount":0,"RunAt":"2026-04-21T15:47:13.7878064Z","CreatedAt":"2026-04-21T15:47:13.7878064Z"}	2026-04-21 15:47:13.788229+00
\.


--
-- Data for Name: Meetings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Meetings" ("Id", "Title", "Description", "Location", "LocationLat", "LocationLng", "StartTime", "EndTime", "RsvpRequired") FROM stdin;
\.


--
-- Data for Name: Sermons; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Sermons" ("Id", "Title", "Description", "S3Key", "DurationSeconds", "Speaker", "PublishedAt", "YoutubeUrl") FROM stdin;
1	css	\N		\N	\N	2026-04-20 00:00:00+00	https://www.youtube.com/watch?v=H9YATJeqShQ
\.


--
-- Data for Name: Tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Tasks" ("Id", "Title", "Description", "CreatedById", "AssigneeId", "TeamId", "Status", "Priority", "DueDate", "CreatedAt", "UpdatedAt", "ClosedAt") FROM stdin;
4	adad	adadad	\N	\N	\N	0	1	2026-03-31 00:00:00+00	2026-03-29 19:45:06.619917+00	\N	\N
3	zxzxz	zxzx	\N	\N	\N	0	1	2026-03-24 00:00:00+00	2026-03-29 19:34:26.370362+00	\N	\N
\.


--
-- Data for Name: Teams; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Teams" ("Id", "Name", "Description", "LeadUserId", "CreatedAt", "UpdatedAt") FROM stdin;
1	Worship Team	Worship Team	5f5e1ed2-2254-4256-a17b-61cb29243b0f	2026-03-27 17:22:43.471227+00	2026-03-28 04:40:35.01073+00
\.


--
-- Data for Name: Timesheets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Timesheets" ("Id", "UserId", "Date", "Hours", "Task", "Notes") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260322131027_InitialCreate	8.0.0
20260413073409_AddAccountingCore	8.0.0
20260420175421_AddRunAtToPayrollRun	8.0.0
20260420181647_AddCreatedAtToPayrollRun	8.0.0
\.


--
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts (id, name, type, created_at) FROM stdin;
1	Cash	ASSET	2026-04-13 09:57:14.134707+00
2	Bank	ASSET	2026-04-13 09:57:14.134707+00
3	Salary Expense	EXPENSE	2026-04-13 09:57:14.134707+00
4	Rent Expense	EXPENSE	2026-04-13 09:57:14.134707+00
5	Utilities Expense	EXPENSE	2026-04-13 09:57:14.134707+00
6	General Expense	EXPENSE	2026-04-13 09:57:14.134707+00
7	Donations	INCOME	2026-04-13 09:57:14.134707+00
8	Church Fund	LIABILITY	2026-04-14 11:07:49.090649+00
9	Opening Balance	LIABILITY	2026-04-14 17:58:34.106544+00
11	HDFC BANK	ASSET	2026-04-17 11:55:16.184004+00
\.


--
-- Data for Name: adminnotifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.adminnotifications (id, userid, type, message, data, isread, createdat) FROM stdin;
\.


--
-- Data for Name: analytics_prayer_overview; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.analytics_prayer_overview (id, snapshot_at, period_label, total_requests, open_requests, closed_requests, testified_requests) FROM stdin;
\.


--
-- Data for Name: analytics_task_by_role; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.analytics_task_by_role (id, role, snapshot_at, total_tasks, completed_tasks, open_tasks, overdue_tasks) FROM stdin;
\.


--
-- Data for Name: analytics_team_productivity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.analytics_team_productivity (id, snapshot_at, team_id, period_label, period_start, period_end, total_hours, avg_hours_per_user) FROM stdin;
\.


--
-- Data for Name: analytics_user_overview; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.analytics_user_overview (id, snapshot_at, total_users, total_admins, total_members, total_staff, total_volunteers, new_members_30d) FROM stdin;
\.


--
-- Data for Name: baptism_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.baptism_requests (id, token, full_name, father_name, mother_name, date_of_birth, contact_number, email, address, church_member_id, preferred_date, preferred_service, church_verified, church_verified_by, church_verified_at, consent_signed, consent_signed_at, consent_signed_by, status, certificate_pdf_url, baptism_date, baptism_place, baptized_by_user_id, created_at, updated_at) FROM stdin;
1	BAP-2026-0001	Sambit Rout	\N	\N	\N	08971124659	sambitrout30@hotmail.com	C/O D.C ROUT, NEAR CHANDI MANDIR	\N	2026-04-26 00:00:00+00	Morning	t	\N	2026-04-16 08:37:37.243394+00	t	2026-04-16 08:37:40.371606+00	\N	Completed	/certificates/baptisms/BaptismCertificate_1_20260416083746.pdf	2026-04-26 00:00:00+00	Mahima Ministry	\N	2026-04-16 08:37:31.776744+00	2026-04-16 08:37:51.289115+00
2	BAP-2026-0002	Sambit Rout	\N	\N	\N	08971124659	sambitrout30@hotmail.com	C/O D.C ROUT, NEAR CHANDI MANDIR	\N	2026-04-17 00:00:00+00	Evening	t	\N	2026-04-16 09:07:45.327666+00	t	2026-04-16 09:07:47.790699+00	\N	Completed	/certificates/baptisms/BaptismCertificate_2_20260416090750.pdf	2026-04-17 00:00:00+00	Mahima Ministry	\N	2026-04-16 09:07:44.117895+00	2026-04-16 09:07:52.686097+00
3	BAP-2026-0003	Sambit Rout	\N	\N	\N	08971124659	sambitrout30@hotmail.com	C/O D.C ROUT, NEAR CHANDI MANDIR	\N	2026-04-26 00:00:00+00	Morning	t	\N	2026-04-17 11:47:55.383457+00	t	2026-04-17 11:48:06.869318+00	\N	Completed	/certificates/baptisms/BaptismCertificate_3_20260417114816.pdf	2026-04-26 00:00:00+00	Mahima Ministry	\N	2026-04-17 11:47:41.160873+00	2026-04-17 11:48:26.421442+00
4	BAP-2026-0004	Sambit Rout	\N	\N	\N	08971124659	sambitrout30@hotmail.com	C/O D.C ROUT, NEAR CHANDI MANDIR	\N	2026-04-26 00:00:00+00	Morning	t	\N	2026-04-17 14:48:10.232904+00	t	2026-04-17 14:48:24.604712+00	\N	Completed	/certificates/baptisms/BaptismCertificate_4_20260417144830.pdf	2026-04-26 00:00:00+00	Mahima Ministry	\N	2026-04-17 14:47:52.419777+00	2026-04-17 14:48:44.426165+00
\.


--
-- Data for Name: candidates; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.candidates (id, full_name, email, phone, is_church_member, member_id, created_at) FROM stdin;
83d0e313-6f5d-4b8c-9597-d947a187ee63	Sambit Rout	sambitrout30@hotmail.com	08971124659	f	\N	2026-04-14 08:02:49.239169+00
\.


--
-- Data for Name: chatmembers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chatmembers (chatid, userid, role, joinedat) FROM stdin;
\.


--
-- Data for Name: chats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chats (id, name, isgroup, createdby, createdat) FROM stdin;
\.


--
-- Data for Name: counselling_cases; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.counselling_cases (id, candidate_id, issue_category, description, status, created_at, closed_at, last_updated_at) FROM stdin;
4919866a-8851-4d30-bc7a-6f8160e7d724	83d0e313-6f5d-4b8c-9597-d947a187ee63	Healing & Deliverance	\N	New	2026-04-14 08:02:49.265197+00	\N	2026-04-14 08:02:49.265197+00
4861ab48-78e8-4b79-949b-c3d9aa2cec58	83d0e313-6f5d-4b8c-9597-d947a187ee63	Spiritual Growth	asasas	New	2026-04-17 11:49:27.151563+00	\N	2026-04-17 11:49:27.151563+00
6593d8d8-1629-41fc-bd5f-40b48618d890	83d0e313-6f5d-4b8c-9597-d947a187ee63	Spiritual Growth	ddddfdf	New	2026-04-17 14:50:17.050325+00	\N	2026-04-17 14:50:17.050325+00
\.


--
-- Data for Name: counselling_sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.counselling_sessions (id, case_id, session_type, status, scheduled_at, location, counselor_id, token_number, token_pdf_url, outcome, notes, created_at, completed_at) FROM stdin;
2d374573-fa23-47d5-bbee-91ee89593404	4919866a-8851-4d30-bc7a-6f8160e7d724	InitialCounselling	Completed	2026-04-18 13:42:00+00	ererer	\N	C-2d374573-20260416	\N	None	fdfdf	2026-04-14 08:02:49.239169+00	2026-04-16 08:18:20.255371+00
22f8c348-68e9-413d-a5f7-0fb9053326f3	4919866a-8851-4d30-bc7a-6f8160e7d724	InitialCounselling	Scheduled	2026-04-24 13:42:00+00	fdd	\N	\N	\N	None	\N	2026-04-16 08:18:20.255371+00	\N
c5e926ec-de91-4ac6-a733-354068d5e5c5	4861ab48-78e8-4b79-949b-c3d9aa2cec58	InitialCounselling	Completed	2026-04-26 17:14:00+00	Pastor's office	\N	C-c5e926ec-20260417	\N	None	sdssd	2026-04-17 11:49:27.146263+00	2026-04-17 11:50:35.168348+00
007853ca-831f-4784-9f5d-111ae5f2f445	4861ab48-78e8-4b79-949b-c3d9aa2cec58	InitialCounselling	Completed	2026-04-26 17:15:00+00	sdsds	\N	\N	\N	None		2026-04-17 11:50:35.168348+00	2026-04-17 11:50:57.124155+00
f0462204-b133-4e55-93de-efacdc595a70	6593d8d8-1629-41fc-bd5f-40b48618d890	InitialCounselling	Completed	2026-04-26 20:15:00+00	Church office	\N	C-f0462204-20260417	\N	None	sdsdsd	2026-04-17 14:50:17.048346+00	2026-04-17 14:51:07.443776+00
\.


--
-- Data for Name: expenses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.expenses (id, description, category, amount, date, vendor, notes, payroll_person, payroll_month, created_at, updated_at, created_by_user_id) FROM stdin;
1	test	RENT	1111.00	2026-03-30		sdssd	\N	\N	2026-03-31 12:59:50.70584+00	2026-03-31 12:59:50.705849+00	\N
2	wwew	RENT	222.00	2026-04-12	\N	\N	\N	\N	2026-04-13 11:36:05.568005+00	2026-04-13 11:36:05.568012+00	\N
3	cv	RENT	242.00	2026-04-12	\N	\N	\N	\N	2026-04-13 11:41:01.628328+00	2026-04-13 11:41:01.628335+00	\N
4	fgfg	RENT	5454.00	2026-04-12	\N	\N	\N	\N	2026-04-13 13:06:55.657118+00	2026-04-13 13:06:55.657118+00	\N
5	ddddf	UTILITIES	4343.00	2026-04-12	\N	\N	\N	\N	2026-04-13 13:07:23.876384+00	2026-04-13 13:07:23.876385+00	\N
\.


--
-- Data for Name: journal_entries; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.journal_entries (id, date, description, created_at) FROM stdin;
1	2026-04-14 00:00:00+00	Opening Balance	2026-04-14 18:12:53.995794+00
2	2026-04-14 00:00:00+00	Vegetables_Saturday Meeting	2026-04-14 18:17:14.612762+00
3	2026-04-15 00:00:00+00	Taxi	2026-04-15 11:08:00.411429+00
4	2026-04-17 00:00:00+00	Saturday Meeting Expense	2026-04-17 11:52:45.19184+00
5	2026-04-17 00:00:00+00	Salary paid to Mr. Balvir	2026-04-17 11:57:10.398185+00
\.


--
-- Data for Name: journal_lines; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.journal_lines (id, journal_entry_id, account_id, debit, credit) FROM stdin;
1	1	2	50000.00	0.00
2	1	1	700.00	0.00
3	1	9	0.00	50700.00
4	2	2	1000.00	0.00
5	2	6	0.00	1000.00
6	3	4	2000.00	0.00
7	3	2	0.00	2000.00
8	4	6	1000.00	0.00
9	4	1	0.00	1000.00
10	5	3	7000.00	0.00
11	5	2	0.00	7000.00
\.


--
-- Data for Name: marriage_applications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.marriage_applications (id, groom_full_name, bride_full_name, groom_phone, bride_phone, groom_email, bride_email, address, groom_is_member, bride_is_member, groom_member_id, bride_member_id, preferred_date, preferred_service, scheduled_at, ceremony_location, status, token, notes, created_at, updated_at, approved_at, approved_by_user_id, completed_at) FROM stdin;
d2e93322-e56c-435c-9524-1dfe2d2ac71d	Sambit Rout	Sambit Rout	08971124659		sambitrout30@hotmail.com	sambitrout30@hotmail.com	C/O D.C ROUT, NEAR CHANDI MANDIR	f	f			2026-04-23 00:00:00+00	Morning	2026-04-17 09:20:00+00		Completed	M-d2e93322-20260416		2026-04-16 09:24:49.963517+00	2026-04-16 09:25:31.083644+00	2026-04-16 09:25:18.366626+00	e86ead35-88db-47b7-8b6c-cf6a63149df6	2026-04-16 09:25:31.083611+00
e0c430c2-f5dc-4645-85e2-083b287b2727	Sambit Rout	Sambit Rout	08971124659		sambitrout30@hotmail.com	sambitrout30@hotmail.com	C/O D.C ROUT, NEAR CHANDI MANDIR	f	f			2026-04-23 00:00:00+00	Morning	2026-04-23 11:41:00+00		Completed	M-e0c430c2-20260417		2026-04-17 11:46:35.451016+00	2026-04-17 11:47:10.018918+00	2026-04-17 11:46:43.753923+00	96e254e4-2767-4c7a-913a-803a5e9b4380	2026-04-17 11:47:10.018847+00
\.


--
-- Data for Name: messagereads; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.messagereads (messageid, userid, readat) FROM stdin;
\.


--
-- Data for Name: messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.messages (id, chatid, senderid, content, contenttype, attachmenturl, createdat) FROM stdin;
\.


--
-- Data for Name: pages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pages (key, id, title, description, created_at, updated_at) FROM stdin;
DASHBOARD	\N	Dashboard	Main dashboard	\N	\N
USERS	\N	Users	User management	\N	\N
TEAMS	\N	Teams	Team management	\N	\N
TASKS	\N	Tasks	Task management	\N	\N
ROLES	\N	Roles	Role management	\N	\N
PAGES	\N	Pages	Page permissions	\N	\N
PAYROLL	\N	Payroll	Payroll management	\N	\N
PRAYER_REQUESTS	\N	Prayer Requests	Prayer requests management	\N	\N
ATTENDANCE	\N	Attendance	Attendance tracking	\N	\N
MARRIAGE	\N	Marriage	Marriage records	\N	\N
BAPTISM	\N	Baptism	Baptism records	\N	\N
COUNSELLING	\N	Counselling	Counselling records	\N	\N
COSTS	\N	Costs	Cost management	\N	\N
SERMONS	\N	SERMONS	SERMONS	2026-04-19 14:44:08.816376+00	2026-04-19 14:44:08.816376+00
\.


--
-- Data for Name: payroll_runs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payroll_runs (id, user_id, staff_name, from_date, to_date, total_hours, hourly_rate, fixed_amount, allowances, deductions, gross_amount, net_amount, run_at, "CreatedAt") FROM stdin;
bffa2775-0c43-4b35-b6c7-e75a4ff280c8	b327b6fc-8104-4a04-a308-0a5172058511	\N	2026-04-01 00:00:00+00	2026-04-30 00:00:00+00	27.00	18.51	5000.00	0.00	0.00	499.77	499.77	2026-04-21 08:12:32.450815+00	2026-04-21 08:12:32.450815+00
b50943ff-edca-47c7-b35b-6f1affb3c368	55f32493-dd32-4230-a2fe-cf23e7801926	\N	2026-04-01 00:00:00+00	2026-04-30 00:00:00+00	18.00	20.00	0.00	0.00	0.00	360.00	360.00	2026-04-21 08:15:40.26673+00	2026-04-21 08:15:40.26673+00
20f7e57f-e377-4e67-b571-85dd8bc61d2c	b327b6fc-8104-4a04-a308-0a5172058511	\N	2026-04-01 00:00:00+00	2026-04-30 00:00:00+00	27.00	18.51	5000.00	0.00	500.00	499.77	0.00	2026-04-21 15:47:13.787806+00	2026-04-21 15:47:13.787806+00
\.


--
-- Data for Name: prayerrequests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prayerrequests (id, userid, title, message, anonymous, status, assignedto, createdat, createdby, closecomment) FROM stdin;
9	b327b6fc-8104-4a04-a308-0a5172058511	Gg	Cgg	f	new	\N	2026-04-21 15:42:48.688006+00	DineshR	\N
8	91ac3e52-0966-4c72-8fa6-22c52afa5e80	Health issues	Please pray for my health problem...back pain	f	closed	\N	2026-04-21 15:29:12.722345+00	VinodhK	\N
\.


--
-- Data for Name: prayerresponses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prayerresponses (id, prayerrequestid, userid, message, author, createdat, updatedat) FROM stdin;
4	8	\N	Ok brother.. we have prayed for you .God bless u .	PawanK	2026-04-21 15:30:06.41738+00	\N
5	8	\N	Testimony - God did a miracle and I am hraled	VinodhK	2026-04-21 15:44:13.703225+00	\N
\.


--
-- Data for Name: role_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.role_permissions (id, role_id, page_key) FROM stdin;
18	12	USERS
19	12	ATTENDANCE
20	12	BAPTISM
21	12	COSTS
22	12	COUNSELLING
23	12	PAYROLL
24	12	PAGES
25	12	MARRIAGE
26	12	DASHBOARD
27	12	PRAYER_REQUESTS
28	12	ROLES
29	12	TASKS
30	12	TEAMS
55	11	PRAYER_REQUESTS
56	11	ATTENDANCE
57	11	TASKS
58	11	COSTS
59	2	DASHBOARD
60	2	PRAYER_REQUESTS
61	10	PRAYER_REQUESTS
62	10	TASKS
63	10	DASHBOARD
77	1	DASHBOARD
78	1	USERS
79	1	TEAMS
80	1	TASKS
81	1	ROLES
82	1	PAGES
83	1	PAYROLL
84	1	PRAYER_REQUESTS
85	1	ATTENDANCE
86	1	MARRIAGE
87	1	BAPTISM
88	1	COUNSELLING
89	1	COSTS
90	1	S
91	1	SERMONS
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, name, description, created_at, updated_at) FROM stdin;
12	Pastor	Church pastor role	2026-03-31 18:49:01.538973+00	\N
11	Staff	Church staff role	2026-03-31 18:49:01.538973+00	\N
2	Member	Church member role	2026-03-25 08:40:50.362646+00	2026-03-31 18:51:43.855522+00
10	Volunteer	Church volunteer role	2026-03-31 18:49:01.538973+00	\N
1	admin	Administrator role	2026-03-25 08:40:50.362646+00	2026-03-31 18:41:55.815492+00
\.


--
-- Data for Name: staff_payroll_settings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.staff_payroll_settings (id, user_id, hourly_rate, monthly_fixed_amount, allowances, deductions, is_active, "ExpectedMonthlyHours", "SalaryType") FROM stdin;
1	165d058d-bda0-4a9c-926e-421f6f703f04	37.03	0.00	0.00	0.00	t	0.0	
2	91ac3e52-0966-4c72-8fa6-22c52afa5e80	11.11	0.00	0.00	0.00	t	0.0	
3	b327b6fc-8104-4a04-a308-0a5172058511	18.51	5000.00	0.00	0.00	t	0	Fixed
4	55f32493-dd32-4230-a2fe-cf23e7801926	20.00	0.00	0.00	0.00	t	0	Fixed
\.


--
-- Data for Name: teammembers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teammembers (teamid, userid, "RoleInTeam", "JoinedAt", "IsLeader") FROM stdin;
1	96e254e4-2767-4c7a-913a-803a5e9b4380	admin	2026-03-28 05:24:20.432988+00	f
1	5f5e1ed2-2254-4256-a17b-61cb29243b0f	Member	2026-03-31 18:34:44.467706+00	t
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, "UserCode", cognitosub, username, email, phone, displayname, role, joindate, lastlogin, "MaritalStatus", "Sex", "IsBaptized", "BaptismPlace", "BaptismDate", "IsBornAgain", "IsBeliever", "Birthday", "Age", "AadharNumber", "HomeAddress", "CurrentAddress", "EmergencyContactPhone", "IsPastor", passwordhash) FROM stdin;
96e254e4-2767-4c7a-913a-803a5e9b4380	admin	\N	PawanK	Pawan.Kumar@Mahimaministries.in	\N	Pawan Kumar	1	2026-03-24 14:44:06+00	\N		Male	t		\N	t	t	\N	\N	821490409138				\N	AQAAAAIAAYagAAAAEMMIEgXmLscv3kG1HuGpDMOlqZ42G0sHKTqcyuCMdhvuQs2QJUtmaJFuYhmtzZpC2w==
5f5e1ed2-2254-4256-a17b-61cb29243b0f	MHN000005	\N	SomaM	Soma.Masih@Mahimaministries.in	+918971124659	Soma Masih	1	2026-03-25 10:28:26+00	\N	\N	Female	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	AQAAAAIAAYagAAAAEFSmqVtDTtciHGL6QomT79VnyroYBpolROMXFNRAWqg0LaAgsYXfX3VkJFNaNg2MjA==
91ac3e52-0966-4c72-8fa6-22c52afa5e80	MHN000014	\N	VinodhK	\N	\N	Vinodh Kumar	2	2026-04-16 13:27:23+00	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	AQAAAAIAAYagAAAAEPdyeiNu7HEpOYBxPoQQ0V80aGnnR8/tLAs6H8+obU3HaX0NiOpjG1zHVztt2BtROQ==
b327b6fc-8104-4a04-a308-0a5172058511	MHN000015	\N	DineshR	\N	\N	Dinesh Rout	11	2026-04-17 01:17:07+00	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	AQAAAAIAAYagAAAAECOtSHRdoCKwK0T3RCamEINdOkNVqGq3+/dcBFxSrwCv08GJwZR3dPgRJ46XWmyaTw==
55f32493-dd32-4230-a2fe-cf23e7801926	MHN000008	\N	SimiR	\N	\N	Sneha Rout	11	2026-03-26 20:19:50+00	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	AQAAAAIAAYagAAAAEO0eZKAuZUso8tCKwZ6Wa8kH5D+0bCpt2aOWbomT3VFFPffIxmD8PaUSVTsnQ/G2/g==
\.


--
-- Name: Attachments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Attachments_Id_seq"', 1, false);


--
-- Name: AttendanceRecords_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AttendanceRecords_Id_seq"', 28, true);


--
-- Name: AuditLogs_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AuditLogs_Id_seq"', 111, true);


--
-- Name: Meetings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Meetings_Id_seq"', 1, false);


--
-- Name: Sermons_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Sermons_Id_seq"', 1, true);


--
-- Name: Tasks_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Tasks_Id_seq"', 5, true);


--
-- Name: Teams_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Teams_Id_seq"', 2, true);


--
-- Name: Timesheets_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Timesheets_Id_seq"', 9, true);


--
-- Name: accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_id_seq', 11, true);


--
-- Name: adminnotifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.adminnotifications_id_seq', 1, false);


--
-- Name: analytics_prayer_overview_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.analytics_prayer_overview_id_seq', 1, false);


--
-- Name: analytics_task_by_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.analytics_task_by_role_id_seq', 1, false);


--
-- Name: analytics_team_productivity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.analytics_team_productivity_id_seq', 1, false);


--
-- Name: analytics_user_overview_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.analytics_user_overview_id_seq', 1, false);


--
-- Name: baptism_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.baptism_requests_id_seq', 4, true);


--
-- Name: expenses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.expenses_id_seq', 5, true);


--
-- Name: journal_entries_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.journal_entries_id_seq', 5, true);


--
-- Name: journal_lines_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.journal_lines_id_seq', 11, true);


--
-- Name: prayerrequests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prayerrequests_id_seq', 9, true);


--
-- Name: prayerresponses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prayerresponses_id_seq', 5, true);


--
-- Name: role_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_permissions_id_seq', 91, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 13, true);


--
-- Name: staff_payroll_settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.staff_payroll_settings_id_seq', 4, true);


--
-- Name: user_code_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_code_seq', 16, true);


--
-- Name: Attachments PK_Attachments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Attachments"
    ADD CONSTRAINT "PK_Attachments" PRIMARY KEY ("Id");


--
-- Name: AttendanceRecords PK_AttendanceRecords; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AttendanceRecords"
    ADD CONSTRAINT "PK_AttendanceRecords" PRIMARY KEY ("Id");


--
-- Name: AuditLogs PK_AuditLogs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AuditLogs"
    ADD CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id");


--
-- Name: Meetings PK_Meetings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Meetings"
    ADD CONSTRAINT "PK_Meetings" PRIMARY KEY ("Id");


--
-- Name: Sermons PK_Sermons; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sermons"
    ADD CONSTRAINT "PK_Sermons" PRIMARY KEY ("Id");


--
-- Name: Tasks PK_Tasks; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id");


--
-- Name: Teams PK_Teams; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Teams"
    ADD CONSTRAINT "PK_Teams" PRIMARY KEY ("Id");


--
-- Name: Timesheets PK_Timesheets; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Timesheets"
    ADD CONSTRAINT "PK_Timesheets" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: accounts PK_accounts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT "PK_accounts" PRIMARY KEY (id);


--
-- Name: adminnotifications PK_adminnotifications; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adminnotifications
    ADD CONSTRAINT "PK_adminnotifications" PRIMARY KEY (id);


--
-- Name: analytics_prayer_overview PK_analytics_prayer_overview; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analytics_prayer_overview
    ADD CONSTRAINT "PK_analytics_prayer_overview" PRIMARY KEY (id);


--
-- Name: analytics_task_by_role PK_analytics_task_by_role; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analytics_task_by_role
    ADD CONSTRAINT "PK_analytics_task_by_role" PRIMARY KEY (id);


--
-- Name: analytics_team_productivity PK_analytics_team_productivity; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analytics_team_productivity
    ADD CONSTRAINT "PK_analytics_team_productivity" PRIMARY KEY (id);


--
-- Name: analytics_user_overview PK_analytics_user_overview; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analytics_user_overview
    ADD CONSTRAINT "PK_analytics_user_overview" PRIMARY KEY (id);


--
-- Name: baptism_requests PK_baptism_requests; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.baptism_requests
    ADD CONSTRAINT "PK_baptism_requests" PRIMARY KEY (id);


--
-- Name: candidates PK_candidates; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT "PK_candidates" PRIMARY KEY (id);


--
-- Name: chatmembers PK_chatmembers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chatmembers
    ADD CONSTRAINT "PK_chatmembers" PRIMARY KEY (chatid, userid);


--
-- Name: chats PK_chats; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT "PK_chats" PRIMARY KEY (id);


--
-- Name: counselling_cases PK_counselling_cases; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.counselling_cases
    ADD CONSTRAINT "PK_counselling_cases" PRIMARY KEY (id);


--
-- Name: counselling_sessions PK_counselling_sessions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.counselling_sessions
    ADD CONSTRAINT "PK_counselling_sessions" PRIMARY KEY (id);


--
-- Name: expenses PK_expenses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT "PK_expenses" PRIMARY KEY (id);


--
-- Name: journal_entries PK_journal_entries; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.journal_entries
    ADD CONSTRAINT "PK_journal_entries" PRIMARY KEY (id);


--
-- Name: journal_lines PK_journal_lines; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.journal_lines
    ADD CONSTRAINT "PK_journal_lines" PRIMARY KEY (id);


--
-- Name: marriage_applications PK_marriage_applications; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marriage_applications
    ADD CONSTRAINT "PK_marriage_applications" PRIMARY KEY (id);


--
-- Name: messagereads PK_messagereads; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messagereads
    ADD CONSTRAINT "PK_messagereads" PRIMARY KEY (messageid, userid);


--
-- Name: messages PK_messages; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT "PK_messages" PRIMARY KEY (id);


--
-- Name: pages PK_pages; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pages
    ADD CONSTRAINT "PK_pages" PRIMARY KEY (key);


--
-- Name: payroll_runs PK_payroll_runs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payroll_runs
    ADD CONSTRAINT "PK_payroll_runs" PRIMARY KEY (id);


--
-- Name: prayerrequests PK_prayerrequests; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prayerrequests
    ADD CONSTRAINT "PK_prayerrequests" PRIMARY KEY (id);


--
-- Name: prayerresponses PK_prayerresponses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prayerresponses
    ADD CONSTRAINT "PK_prayerresponses" PRIMARY KEY (id);


--
-- Name: role_permissions PK_role_permissions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT "PK_role_permissions" PRIMARY KEY (id);


--
-- Name: roles PK_roles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT "PK_roles" PRIMARY KEY (id);


--
-- Name: staff_payroll_settings PK_staff_payroll_settings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.staff_payroll_settings
    ADD CONSTRAINT "PK_staff_payroll_settings" PRIMARY KEY (id);


--
-- Name: teammembers PK_teammembers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teammembers
    ADD CONSTRAINT "PK_teammembers" PRIMARY KEY (teamid, userid);


--
-- Name: users PK_users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT "PK_users" PRIMARY KEY (id);


--
-- Name: roles roles_name_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_name_unique UNIQUE (name);


--
-- Name: role_permissions uq_role_permissions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT uq_role_permissions UNIQUE (role_id, page_key);


--
-- Name: roles uq_roles_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uq_roles_name UNIQUE (name);


--
-- Name: IX_Tasks_AssigneeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tasks_AssigneeId" ON public."Tasks" USING btree ("AssigneeId");


--
-- Name: IX_Tasks_CreatedById; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tasks_CreatedById" ON public."Tasks" USING btree ("CreatedById");


--
-- Name: IX_Tasks_TeamId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tasks_TeamId" ON public."Tasks" USING btree ("TeamId");


--
-- Name: IX_Teams_LeadUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Teams_LeadUserId" ON public."Teams" USING btree ("LeadUserId");


--
-- Name: IX_accounts_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_accounts_name" ON public.accounts USING btree (name);


--
-- Name: IX_adminnotifications_userid_isread; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_adminnotifications_userid_isread" ON public.adminnotifications USING btree (userid, isread);


--
-- Name: IX_analytics_team_productivity_team_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_analytics_team_productivity_team_id" ON public.analytics_team_productivity USING btree (team_id);


--
-- Name: IX_chatmembers_userid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_chatmembers_userid" ON public.chatmembers USING btree (userid);


--
-- Name: IX_chats_createdby; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_chats_createdby" ON public.chats USING btree (createdby);


--
-- Name: IX_counselling_cases_candidate_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_counselling_cases_candidate_id" ON public.counselling_cases USING btree (candidate_id);


--
-- Name: IX_counselling_sessions_case_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_counselling_sessions_case_id" ON public.counselling_sessions USING btree (case_id);


--
-- Name: IX_journal_lines_account_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_journal_lines_account_id" ON public.journal_lines USING btree (account_id);


--
-- Name: IX_journal_lines_journal_entry_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_journal_lines_journal_entry_id" ON public.journal_lines USING btree (journal_entry_id);


--
-- Name: IX_marriage_applications_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_marriage_applications_status" ON public.marriage_applications USING btree (status);


--
-- Name: IX_messagereads_userid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_messagereads_userid" ON public.messagereads USING btree (userid);


--
-- Name: IX_messages_chatid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_messages_chatid" ON public.messages USING btree (chatid);


--
-- Name: IX_messages_senderid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_messages_senderid" ON public.messages USING btree (senderid);


--
-- Name: IX_payroll_runs_user_id_from_date_to_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_payroll_runs_user_id_from_date_to_date" ON public.payroll_runs USING btree (user_id, from_date, to_date);


--
-- Name: IX_prayerresponses_prayerrequestid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_prayerresponses_prayerrequestid" ON public.prayerresponses USING btree (prayerrequestid);


--
-- Name: IX_role_permissions_role_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_role_permissions_role_id" ON public.role_permissions USING btree (role_id);


--
-- Name: IX_teammembers_userid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_teammembers_userid" ON public.teammembers USING btree (userid);


--
-- Name: IX_users_UserCode; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_users_UserCode" ON public.users USING btree ("UserCode");


--
-- Name: users trg_set_user_code; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_set_user_code BEFORE INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_user_code();


--
-- Name: Tasks FK_Tasks_Teams_TeamId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "FK_Tasks_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES public."Teams"("Id");


--
-- Name: Tasks FK_Tasks_users_AssigneeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "FK_Tasks_users_AssigneeId" FOREIGN KEY ("AssigneeId") REFERENCES public.users(id);


--
-- Name: Tasks FK_Tasks_users_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "FK_Tasks_users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public.users(id);


--
-- Name: Teams FK_Teams_users_LeadUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Teams"
    ADD CONSTRAINT "FK_Teams_users_LeadUserId" FOREIGN KEY ("LeadUserId") REFERENCES public.users(id);


--
-- Name: journal_lines FK_journal_lines_accounts_account_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.journal_lines
    ADD CONSTRAINT "FK_journal_lines_accounts_account_id" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE RESTRICT;


--
-- Name: journal_lines FK_journal_lines_journal_entries_journal_entry_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.journal_lines
    ADD CONSTRAINT "FK_journal_lines_journal_entries_journal_entry_id" FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE CASCADE;


--
-- Name: role_permissions FK_role_permissions_roles_role_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT "FK_role_permissions_roles_role_id" FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE;


--
-- Name: teammembers FK_teammembers_Teams_teamid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teammembers
    ADD CONSTRAINT "FK_teammembers_Teams_teamid" FOREIGN KEY (teamid) REFERENCES public."Teams"("Id") ON DELETE CASCADE;


--
-- Name: teammembers FK_teammembers_users_userid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teammembers
    ADD CONSTRAINT "FK_teammembers_users_userid" FOREIGN KEY (userid) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: adminnotifications fk_adminnotifications_userid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adminnotifications
    ADD CONSTRAINT fk_adminnotifications_userid FOREIGN KEY (userid) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: analytics_team_productivity fk_analytics_team_productivity_teamid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analytics_team_productivity
    ADD CONSTRAINT fk_analytics_team_productivity_teamid FOREIGN KEY (team_id) REFERENCES public."Teams"("Id") ON DELETE RESTRICT;


--
-- Name: chatmembers fk_chatmembers_chatid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chatmembers
    ADD CONSTRAINT fk_chatmembers_chatid FOREIGN KEY (chatid) REFERENCES public.chats(id) ON DELETE CASCADE;


--
-- Name: chatmembers fk_chatmembers_userid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chatmembers
    ADD CONSTRAINT fk_chatmembers_userid FOREIGN KEY (userid) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: chats fk_chats_createdby; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT fk_chats_createdby FOREIGN KEY (createdby) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: counselling_cases fk_counsellingcases_candidateid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.counselling_cases
    ADD CONSTRAINT fk_counsellingcases_candidateid FOREIGN KEY (candidate_id) REFERENCES public.candidates(id) ON DELETE CASCADE;


--
-- Name: counselling_sessions fk_counsellingsessions_caseid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.counselling_sessions
    ADD CONSTRAINT fk_counsellingsessions_caseid FOREIGN KEY (case_id) REFERENCES public.counselling_cases(id) ON DELETE CASCADE;


--
-- Name: messagereads fk_messagereads_messageid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messagereads
    ADD CONSTRAINT fk_messagereads_messageid FOREIGN KEY (messageid) REFERENCES public.messages(id) ON DELETE CASCADE;


--
-- Name: messagereads fk_messagereads_userid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messagereads
    ADD CONSTRAINT fk_messagereads_userid FOREIGN KEY (userid) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: messages fk_messages_chatid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk_messages_chatid FOREIGN KEY (chatid) REFERENCES public.chats(id) ON DELETE CASCADE;


--
-- Name: messages fk_messages_senderid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk_messages_senderid FOREIGN KEY (senderid) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: prayerresponses fk_prayerresponses_prayerrequest; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prayerresponses
    ADD CONSTRAINT fk_prayerresponses_prayerrequest FOREIGN KEY (prayerrequestid) REFERENCES public.prayerrequests(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict nOoLkPEeOl0vpEasa2IA4N2bgeTYeV0TiJ3defnDnm0vnbJFO6KJE9nDVDAyHr9

