--
-- PostgreSQL database dump
--

\restrict mPSXgheewY5LY7gZeOlHPYam2JNNoMwrv74PyZ97qaE5AFlwkzVx711ARbQM1Lr

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


--
-- Name: generate_user_code(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.generate_user_code() RETURNS text
    LANGUAGE plpgsql
    AS $$
DECLARE
    seq_num INT;
BEGIN
    seq_num := nextval('user_code_seq');
    RETURN 'MHN' || LPAD(seq_num::TEXT, 6, '0');
END;
$$;


ALTER FUNCTION public.generate_user_code() OWNER TO postgres;

--
-- Name: set_user_code(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.set_user_code() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF NEW."UserCode" IS NULL THEN
        NEW."UserCode" := generate_user_code();
    END IF;
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.set_user_code() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Attachments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Attachments" (
    "Id" bigint NOT NULL,
    "OwnerType" text NOT NULL,
    "OwnerId" bigint NOT NULL,
    "S3Key" text NOT NULL,
    "Filename" text,
    "ContentType" text,
    "SizeBytes" bigint,
    "UploadedBy" uuid,
    "UploadedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Attachments" OWNER TO postgres;

--
-- Name: Attachments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Attachments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Attachments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AttendanceRecords; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AttendanceRecords" (
    "Id" integer NOT NULL,
    "UserId" character varying(128) NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Status" character varying(64) NOT NULL
);


ALTER TABLE public."AttendanceRecords" OWNER TO postgres;

--
-- Name: AttendanceRecords_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AttendanceRecords" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AttendanceRecords_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AuditLogs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AuditLogs" (
    "Id" bigint NOT NULL,
    "ActorId" uuid,
    "Action" text NOT NULL,
    "EntityType" text,
    "EntityId" text,
    "Details" text,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."AuditLogs" OWNER TO postgres;

--
-- Name: AuditLogs_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AuditLogs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AuditLogs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Meetings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Meetings" (
    "Id" bigint NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "Location" text,
    "LocationLat" numeric,
    "LocationLng" numeric,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone,
    "RsvpRequired" boolean NOT NULL
);


ALTER TABLE public."Meetings" OWNER TO postgres;

--
-- Name: Meetings_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Meetings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Meetings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Sermons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sermons" (
    "Id" bigint NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "S3Key" text NOT NULL,
    "DurationSeconds" integer,
    "Speaker" text,
    "PublishedAt" timestamp with time zone NOT NULL,
    "YoutubeUrl" text
);


ALTER TABLE public."Sermons" OWNER TO postgres;

--
-- Name: Sermons_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Sermons" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sermons_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tasks" (
    "Id" bigint NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "CreatedById" uuid,
    "AssigneeId" uuid,
    "TeamId" bigint,
    "Status" integer NOT NULL,
    "Priority" integer NOT NULL,
    "DueDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ClosedAt" timestamp with time zone
);


ALTER TABLE public."Tasks" OWNER TO postgres;

--
-- Name: Tasks_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tasks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tasks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Teams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Teams" (
    "Id" bigint NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "LeadUserId" uuid,
    "CreatedAt" timestamp with time zone DEFAULT now(),
    "UpdatedAt" timestamp with time zone DEFAULT now()
);


ALTER TABLE public."Teams" OWNER TO postgres;

--
-- Name: Teams_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Teams" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Teams_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Timesheets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Timesheets" (
    "Id" integer NOT NULL,
    "UserId" character varying(128) NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Hours" numeric NOT NULL,
    "Task" character varying(512),
    "Notes" character varying(2048)
);


ALTER TABLE public."Timesheets" OWNER TO postgres;

--
-- Name: Timesheets_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Timesheets" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Timesheets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "UserCode" character varying(16) NOT NULL,
    cognitosub text,
    username text,
    email text,
    phone text,
    displayname text,
    role text DEFAULT 'Member'::text NOT NULL,
    joindate timestamp with time zone DEFAULT now() NOT NULL,
    lastlogin timestamp with time zone,
    "MaritalStatus" text,
    "Sex" text,
    "IsBaptized" boolean,
    "BaptismPlace" text,
    "BaptismDate" timestamp with time zone,
    "IsBornAgain" boolean,
    "IsBeliever" boolean,
    "Birthday" timestamp with time zone,
    "Age" integer,
    "AadharNumber" text,
    "HomeAddress" text,
    "CurrentAddress" text,
    "EmergencyContactPhone" text,
    "IsPastor" boolean,
    passwordhash text
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: Users; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public."Users" AS
 SELECT id,
    "UserCode",
    cognitosub,
    username,
    email,
    phone,
    displayname,
    role,
    joindate,
    lastlogin,
    "MaritalStatus",
    "Sex",
    "IsBaptized",
    "BaptismPlace",
    "BaptismDate",
    "IsBornAgain",
    "IsBeliever",
    "Birthday",
    "Age",
    "AadharNumber",
    "HomeAddress",
    "CurrentAddress",
    "EmergencyContactPhone",
    "IsPastor"
   FROM public.users;


ALTER VIEW public."Users" OWNER TO postgres;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    type character varying(50) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: adminnotifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.adminnotifications (
    id bigint NOT NULL,
    userid uuid,
    type character varying(200) NOT NULL,
    message text,
    data text,
    isread boolean DEFAULT false NOT NULL,
    createdat timestamp with time zone NOT NULL
);


ALTER TABLE public.adminnotifications OWNER TO postgres;

--
-- Name: adminnotifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.adminnotifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.adminnotifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analytics_prayer_overview; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.analytics_prayer_overview (
    id integer NOT NULL,
    snapshot_at timestamp with time zone NOT NULL,
    period_label text NOT NULL,
    total_requests integer NOT NULL,
    open_requests integer NOT NULL,
    closed_requests integer NOT NULL,
    testified_requests integer NOT NULL
);


ALTER TABLE public.analytics_prayer_overview OWNER TO postgres;

--
-- Name: analytics_prayer_overview_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.analytics_prayer_overview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analytics_prayer_overview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analytics_task_by_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.analytics_task_by_role (
    id integer NOT NULL,
    role text NOT NULL,
    snapshot_at timestamp with time zone NOT NULL,
    total_tasks integer NOT NULL,
    completed_tasks integer NOT NULL,
    open_tasks integer NOT NULL,
    overdue_tasks integer NOT NULL
);


ALTER TABLE public.analytics_task_by_role OWNER TO postgres;

--
-- Name: analytics_task_by_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.analytics_task_by_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analytics_task_by_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analytics_team_productivity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.analytics_team_productivity (
    id integer NOT NULL,
    snapshot_at timestamp with time zone NOT NULL,
    team_id bigint NOT NULL,
    period_label text NOT NULL,
    period_start timestamp with time zone NOT NULL,
    period_end timestamp with time zone NOT NULL,
    total_hours double precision NOT NULL,
    avg_hours_per_user double precision NOT NULL
);


ALTER TABLE public.analytics_team_productivity OWNER TO postgres;

--
-- Name: analytics_team_productivity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.analytics_team_productivity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analytics_team_productivity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analytics_user_overview; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.analytics_user_overview (
    id integer NOT NULL,
    snapshot_at timestamp with time zone NOT NULL,
    total_users integer NOT NULL,
    total_admins integer NOT NULL,
    total_members integer NOT NULL,
    total_staff integer NOT NULL,
    total_volunteers integer NOT NULL,
    new_members_30d integer NOT NULL
);


ALTER TABLE public.analytics_user_overview OWNER TO postgres;

--
-- Name: analytics_user_overview_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.analytics_user_overview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analytics_user_overview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: baptism_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.baptism_requests (
    id integer NOT NULL,
    token text,
    full_name text NOT NULL,
    father_name text,
    mother_name text,
    date_of_birth timestamp with time zone,
    contact_number text,
    email text,
    address text,
    church_member_id integer,
    preferred_date timestamp with time zone,
    preferred_service text,
    church_verified boolean NOT NULL,
    church_verified_by integer,
    church_verified_at timestamp with time zone,
    consent_signed boolean NOT NULL,
    consent_signed_at timestamp with time zone,
    consent_signed_by integer,
    status text DEFAULT 'Pending'::text NOT NULL,
    certificate_pdf_url text,
    baptism_date timestamp with time zone,
    baptism_place text,
    baptized_by_user_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.baptism_requests OWNER TO postgres;

--
-- Name: baptism_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.baptism_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.baptism_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: candidates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.candidates (
    id uuid NOT NULL,
    full_name character varying(150) NOT NULL,
    email character varying(200),
    phone character varying(20) NOT NULL,
    is_church_member boolean NOT NULL,
    member_id text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.candidates OWNER TO postgres;

--
-- Name: chatmembers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chatmembers (
    chatid uuid NOT NULL,
    userid uuid NOT NULL,
    role character varying(50) NOT NULL,
    joinedat timestamp with time zone NOT NULL
);


ALTER TABLE public.chatmembers OWNER TO postgres;

--
-- Name: chats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chats (
    id uuid NOT NULL,
    name text,
    isgroup boolean NOT NULL,
    createdby uuid NOT NULL,
    createdat timestamp with time zone NOT NULL
);


ALTER TABLE public.chats OWNER TO postgres;

--
-- Name: counselling_cases; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.counselling_cases (
    id uuid NOT NULL,
    candidate_id uuid NOT NULL,
    issue_category character varying(100) NOT NULL,
    description text,
    status character varying(30) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    closed_at timestamp with time zone,
    last_updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.counselling_cases OWNER TO postgres;

--
-- Name: counselling_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.counselling_sessions (
    id uuid NOT NULL,
    case_id uuid NOT NULL,
    session_type character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    scheduled_at timestamp with time zone,
    location character varying(150),
    counselor_id uuid,
    token_number character varying(50),
    token_pdf_url text,
    outcome character varying(40) NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone
);


ALTER TABLE public.counselling_sessions OWNER TO postgres;

--
-- Name: expenses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.expenses (
    id bigint NOT NULL,
    description text NOT NULL,
    category character varying(64) NOT NULL,
    amount numeric(12,2) NOT NULL,
    date date NOT NULL,
    vendor text,
    notes text,
    payroll_person text,
    payroll_month character varying(7),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by_user_id bigint
);


ALTER TABLE public.expenses OWNER TO postgres;

--
-- Name: expenses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: journal_entries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.journal_entries (
    id bigint NOT NULL,
    date timestamp with time zone NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.journal_entries OWNER TO postgres;

--
-- Name: journal_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.journal_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.journal_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: journal_lines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.journal_lines (
    id bigint NOT NULL,
    journal_entry_id bigint NOT NULL,
    account_id bigint NOT NULL,
    debit numeric(12,2) NOT NULL,
    credit numeric(12,2) NOT NULL
);


ALTER TABLE public.journal_lines OWNER TO postgres;

--
-- Name: journal_lines_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.journal_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.journal_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: marriage_applications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marriage_applications (
    id uuid NOT NULL,
    groom_full_name character varying(200) NOT NULL,
    bride_full_name character varying(200) NOT NULL,
    groom_phone character varying(32),
    bride_phone character varying(32),
    groom_email character varying(256),
    bride_email character varying(256),
    address text,
    groom_is_member boolean NOT NULL,
    bride_is_member boolean NOT NULL,
    groom_member_id character varying(64),
    bride_member_id character varying(64),
    preferred_date timestamp with time zone,
    preferred_service character varying(64),
    scheduled_at timestamp with time zone,
    ceremony_location character varying(256),
    status character varying(64) NOT NULL,
    token character varying(50),
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    approved_at timestamp with time zone,
    approved_by_user_id character varying(128),
    completed_at timestamp with time zone
);


ALTER TABLE public.marriage_applications OWNER TO postgres;

--
-- Name: messagereads; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messagereads (
    messageid uuid NOT NULL,
    userid uuid NOT NULL,
    readat timestamp with time zone NOT NULL
);


ALTER TABLE public.messagereads OWNER TO postgres;

--
-- Name: messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messages (
    id uuid NOT NULL,
    chatid uuid NOT NULL,
    senderid uuid NOT NULL,
    content text,
    contenttype text NOT NULL,
    attachmenturl text,
    createdat timestamp with time zone NOT NULL
);


ALTER TABLE public.messages OWNER TO postgres;

--
-- Name: pages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pages (
    key character varying(200) NOT NULL,
    id integer,
    title text,
    description text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);


ALTER TABLE public.pages OWNER TO postgres;

--
-- Name: payroll_runs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payroll_runs (
    id uuid NOT NULL,
    user_id character varying(128) NOT NULL,
    staff_name character varying(256),
    from_date timestamp with time zone NOT NULL,
    to_date timestamp with time zone NOT NULL,
    total_hours numeric(18,2) NOT NULL,
    hourly_rate numeric(18,2) NOT NULL,
    fixed_amount numeric(18,2) NOT NULL,
    allowances numeric(18,2) NOT NULL,
    deductions numeric(18,2) NOT NULL,
    gross_amount numeric(18,2) NOT NULL,
    net_amount numeric(18,2) NOT NULL,
    run_at timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL
);


ALTER TABLE public.payroll_runs OWNER TO postgres;

--
-- Name: prayerrequests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prayerrequests (
    id bigint NOT NULL,
    userid uuid,
    title character varying(500),
    message text,
    anonymous boolean NOT NULL,
    status character varying(50) NOT NULL,
    assignedto uuid,
    createdat timestamp with time zone NOT NULL,
    createdby character varying(200),
    closecomment text
);


ALTER TABLE public.prayerrequests OWNER TO postgres;

--
-- Name: prayerrequests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prayerrequests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prayerrequests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prayerresponses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prayerresponses (
    id bigint NOT NULL,
    prayerrequestid bigint NOT NULL,
    userid uuid,
    message text NOT NULL,
    author character varying(200),
    createdat timestamp with time zone NOT NULL,
    updatedat timestamp with time zone
);


ALTER TABLE public.prayerresponses OWNER TO postgres;

--
-- Name: prayerresponses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prayerresponses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prayerresponses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_permissions (
    id integer NOT NULL,
    role_id integer NOT NULL,
    page_key text NOT NULL
);


ALTER TABLE public.role_permissions OWNER TO postgres;

--
-- Name: role_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: staff_payroll_settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.staff_payroll_settings (
    id integer NOT NULL,
    user_id character varying(128) NOT NULL,
    hourly_rate numeric(18,2) NOT NULL,
    monthly_fixed_amount numeric(18,2),
    allowances numeric(18,2),
    deductions numeric(18,2),
    is_active boolean DEFAULT true NOT NULL,
    "ExpectedMonthlyHours" numeric DEFAULT 0.0 NOT NULL,
    "SalaryType" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public.staff_payroll_settings OWNER TO postgres;

--
-- Name: staff_payroll_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.staff_payroll_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.staff_payroll_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teammembers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teammembers (
    teamid bigint NOT NULL,
    userid uuid NOT NULL,
    "RoleInTeam" text,
    "JoinedAt" timestamp with time zone NOT NULL,
    "IsLeader" boolean DEFAULT false
);


ALTER TABLE public.teammembers OWNER TO postgres;

--
-- Name: user_code_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_code_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_code_seq OWNER TO postgres;

--
-- Name: Attachments PK_Attachments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Attachments"
    ADD CONSTRAINT "PK_Attachments" PRIMARY KEY ("Id");


--
-- Name: AttendanceRecords PK_AttendanceRecords; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AttendanceRecords"
    ADD CONSTRAINT "PK_AttendanceRecords" PRIMARY KEY ("Id");


--
-- Name: AuditLogs PK_AuditLogs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AuditLogs"
    ADD CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id");


--
-- Name: Meetings PK_Meetings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Meetings"
    ADD CONSTRAINT "PK_Meetings" PRIMARY KEY ("Id");


--
-- Name: Sermons PK_Sermons; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sermons"
    ADD CONSTRAINT "PK_Sermons" PRIMARY KEY ("Id");


--
-- Name: Tasks PK_Tasks; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id");


--
-- Name: Teams PK_Teams; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Teams"
    ADD CONSTRAINT "PK_Teams" PRIMARY KEY ("Id");


--
-- Name: Timesheets PK_Timesheets; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Timesheets"
    ADD CONSTRAINT "PK_Timesheets" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: accounts PK_accounts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT "PK_accounts" PRIMARY KEY (id);


--
-- Name: adminnotifications PK_adminnotifications; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adminnotifications
    ADD CONSTRAINT "PK_adminnotifications" PRIMARY KEY (id);


--
-- Name: analytics_prayer_overview PK_analytics_prayer_overview; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analytics_prayer_overview
    ADD CONSTRAINT "PK_analytics_prayer_overview" PRIMARY KEY (id);


--
-- Name: analytics_task_by_role PK_analytics_task_by_role; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analytics_task_by_role
    ADD CONSTRAINT "PK_analytics_task_by_role" PRIMARY KEY (id);


--
-- Name: analytics_team_productivity PK_analytics_team_productivity; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analytics_team_productivity
    ADD CONSTRAINT "PK_analytics_team_productivity" PRIMARY KEY (id);


--
-- Name: analytics_user_overview PK_analytics_user_overview; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analytics_user_overview
    ADD CONSTRAINT "PK_analytics_user_overview" PRIMARY KEY (id);


--
-- Name: baptism_requests PK_baptism_requests; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.baptism_requests
    ADD CONSTRAINT "PK_baptism_requests" PRIMARY KEY (id);


--
-- Name: candidates PK_candidates; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT "PK_candidates" PRIMARY KEY (id);


--
-- Name: chatmembers PK_chatmembers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chatmembers
    ADD CONSTRAINT "PK_chatmembers" PRIMARY KEY (chatid, userid);


--
-- Name: chats PK_chats; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT "PK_chats" PRIMARY KEY (id);


--
-- Name: counselling_cases PK_counselling_cases; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.counselling_cases
    ADD CONSTRAINT "PK_counselling_cases" PRIMARY KEY (id);


--
-- Name: counselling_sessions PK_counselling_sessions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.counselling_sessions
    ADD CONSTRAINT "PK_counselling_sessions" PRIMARY KEY (id);


--
-- Name: expenses PK_expenses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT "PK_expenses" PRIMARY KEY (id);


--
-- Name: journal_entries PK_journal_entries; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.journal_entries
    ADD CONSTRAINT "PK_journal_entries" PRIMARY KEY (id);


--
-- Name: journal_lines PK_journal_lines; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.journal_lines
    ADD CONSTRAINT "PK_journal_lines" PRIMARY KEY (id);


--
-- Name: marriage_applications PK_marriage_applications; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marriage_applications
    ADD CONSTRAINT "PK_marriage_applications" PRIMARY KEY (id);


--
-- Name: messagereads PK_messagereads; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messagereads
    ADD CONSTRAINT "PK_messagereads" PRIMARY KEY (messageid, userid);


--
-- Name: messages PK_messages; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT "PK_messages" PRIMARY KEY (id);


--
-- Name: pages PK_pages; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pages
    ADD CONSTRAINT "PK_pages" PRIMARY KEY (key);


--
-- Name: payroll_runs PK_payroll_runs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payroll_runs
    ADD CONSTRAINT "PK_payroll_runs" PRIMARY KEY (id);


--
-- Name: prayerrequests PK_prayerrequests; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prayerrequests
    ADD CONSTRAINT "PK_prayerrequests" PRIMARY KEY (id);


--
-- Name: prayerresponses PK_prayerresponses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prayerresponses
    ADD CONSTRAINT "PK_prayerresponses" PRIMARY KEY (id);


--
-- Name: role_permissions PK_role_permissions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT "PK_role_permissions" PRIMARY KEY (id);


--
-- Name: roles PK_roles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT "PK_roles" PRIMARY KEY (id);


--
-- Name: staff_payroll_settings PK_staff_payroll_settings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.staff_payroll_settings
    ADD CONSTRAINT "PK_staff_payroll_settings" PRIMARY KEY (id);


--
-- Name: teammembers PK_teammembers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teammembers
    ADD CONSTRAINT "PK_teammembers" PRIMARY KEY (teamid, userid);


--
-- Name: users PK_users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT "PK_users" PRIMARY KEY (id);


--
-- Name: roles roles_name_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_name_unique UNIQUE (name);


--
-- Name: role_permissions uq_role_permissions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT uq_role_permissions UNIQUE (role_id, page_key);


--
-- Name: roles uq_roles_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uq_roles_name UNIQUE (name);


--
-- Name: IX_Tasks_AssigneeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tasks_AssigneeId" ON public."Tasks" USING btree ("AssigneeId");


--
-- Name: IX_Tasks_CreatedById; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tasks_CreatedById" ON public."Tasks" USING btree ("CreatedById");


--
-- Name: IX_Tasks_TeamId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tasks_TeamId" ON public."Tasks" USING btree ("TeamId");


--
-- Name: IX_Teams_LeadUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Teams_LeadUserId" ON public."Teams" USING btree ("LeadUserId");


--
-- Name: IX_accounts_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_accounts_name" ON public.accounts USING btree (name);


--
-- Name: IX_adminnotifications_userid_isread; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_adminnotifications_userid_isread" ON public.adminnotifications USING btree (userid, isread);


--
-- Name: IX_analytics_team_productivity_team_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_analytics_team_productivity_team_id" ON public.analytics_team_productivity USING btree (team_id);


--
-- Name: IX_chatmembers_userid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_chatmembers_userid" ON public.chatmembers USING btree (userid);


--
-- Name: IX_chats_createdby; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_chats_createdby" ON public.chats USING btree (createdby);


--
-- Name: IX_counselling_cases_candidate_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_counselling_cases_candidate_id" ON public.counselling_cases USING btree (candidate_id);


--
-- Name: IX_counselling_sessions_case_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_counselling_sessions_case_id" ON public.counselling_sessions USING btree (case_id);


--
-- Name: IX_journal_lines_account_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_journal_lines_account_id" ON public.journal_lines USING btree (account_id);


--
-- Name: IX_journal_lines_journal_entry_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_journal_lines_journal_entry_id" ON public.journal_lines USING btree (journal_entry_id);


--
-- Name: IX_marriage_applications_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_marriage_applications_status" ON public.marriage_applications USING btree (status);


--
-- Name: IX_messagereads_userid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_messagereads_userid" ON public.messagereads USING btree (userid);


--
-- Name: IX_messages_chatid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_messages_chatid" ON public.messages USING btree (chatid);


--
-- Name: IX_messages_senderid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_messages_senderid" ON public.messages USING btree (senderid);


--
-- Name: IX_payroll_runs_user_id_from_date_to_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_payroll_runs_user_id_from_date_to_date" ON public.payroll_runs USING btree (user_id, from_date, to_date);


--
-- Name: IX_prayerresponses_prayerrequestid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_prayerresponses_prayerrequestid" ON public.prayerresponses USING btree (prayerrequestid);


--
-- Name: IX_role_permissions_role_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_role_permissions_role_id" ON public.role_permissions USING btree (role_id);


--
-- Name: IX_teammembers_userid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_teammembers_userid" ON public.teammembers USING btree (userid);


--
-- Name: IX_users_UserCode; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_users_UserCode" ON public.users USING btree ("UserCode");


--
-- Name: users trg_set_user_code; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_set_user_code BEFORE INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_user_code();


--
-- Name: Tasks FK_Tasks_Teams_TeamId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "FK_Tasks_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES public."Teams"("Id");


--
-- Name: Tasks FK_Tasks_users_AssigneeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "FK_Tasks_users_AssigneeId" FOREIGN KEY ("AssigneeId") REFERENCES public.users(id);


--
-- Name: Tasks FK_Tasks_users_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "FK_Tasks_users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public.users(id);


--
-- Name: Teams FK_Teams_users_LeadUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Teams"
    ADD CONSTRAINT "FK_Teams_users_LeadUserId" FOREIGN KEY ("LeadUserId") REFERENCES public.users(id);


--
-- Name: journal_lines FK_journal_lines_accounts_account_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.journal_lines
    ADD CONSTRAINT "FK_journal_lines_accounts_account_id" FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE RESTRICT;


--
-- Name: journal_lines FK_journal_lines_journal_entries_journal_entry_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.journal_lines
    ADD CONSTRAINT "FK_journal_lines_journal_entries_journal_entry_id" FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE CASCADE;


--
-- Name: role_permissions FK_role_permissions_roles_role_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT "FK_role_permissions_roles_role_id" FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE;


--
-- Name: teammembers FK_teammembers_Teams_teamid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teammembers
    ADD CONSTRAINT "FK_teammembers_Teams_teamid" FOREIGN KEY (teamid) REFERENCES public."Teams"("Id") ON DELETE CASCADE;


--
-- Name: teammembers FK_teammembers_users_userid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teammembers
    ADD CONSTRAINT "FK_teammembers_users_userid" FOREIGN KEY (userid) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: adminnotifications fk_adminnotifications_userid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adminnotifications
    ADD CONSTRAINT fk_adminnotifications_userid FOREIGN KEY (userid) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: analytics_team_productivity fk_analytics_team_productivity_teamid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.analytics_team_productivity
    ADD CONSTRAINT fk_analytics_team_productivity_teamid FOREIGN KEY (team_id) REFERENCES public."Teams"("Id") ON DELETE RESTRICT;


--
-- Name: chatmembers fk_chatmembers_chatid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chatmembers
    ADD CONSTRAINT fk_chatmembers_chatid FOREIGN KEY (chatid) REFERENCES public.chats(id) ON DELETE CASCADE;


--
-- Name: chatmembers fk_chatmembers_userid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chatmembers
    ADD CONSTRAINT fk_chatmembers_userid FOREIGN KEY (userid) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: chats fk_chats_createdby; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT fk_chats_createdby FOREIGN KEY (createdby) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: counselling_cases fk_counsellingcases_candidateid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.counselling_cases
    ADD CONSTRAINT fk_counsellingcases_candidateid FOREIGN KEY (candidate_id) REFERENCES public.candidates(id) ON DELETE CASCADE;


--
-- Name: counselling_sessions fk_counsellingsessions_caseid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.counselling_sessions
    ADD CONSTRAINT fk_counsellingsessions_caseid FOREIGN KEY (case_id) REFERENCES public.counselling_cases(id) ON DELETE CASCADE;


--
-- Name: messagereads fk_messagereads_messageid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messagereads
    ADD CONSTRAINT fk_messagereads_messageid FOREIGN KEY (messageid) REFERENCES public.messages(id) ON DELETE CASCADE;


--
-- Name: messagereads fk_messagereads_userid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messagereads
    ADD CONSTRAINT fk_messagereads_userid FOREIGN KEY (userid) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: messages fk_messages_chatid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk_messages_chatid FOREIGN KEY (chatid) REFERENCES public.chats(id) ON DELETE CASCADE;


--
-- Name: messages fk_messages_senderid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk_messages_senderid FOREIGN KEY (senderid) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: prayerresponses fk_prayerresponses_prayerrequest; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prayerresponses
    ADD CONSTRAINT fk_prayerresponses_prayerrequest FOREIGN KEY (prayerrequestid) REFERENCES public.prayerrequests(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict mPSXgheewY5LY7gZeOlHPYam2JNNoMwrv74PyZ97qaE5AFlwkzVx711ARbQM1Lr

