import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, AudioLines, BrainCircuit, Camera, CirclePlus, Copy, Film, Grid2X2, Layers3, Mic, MonitorUp, Play, Radio, RefreshCw, Save, ScanLine, ScreenShare, Square, Trash2, Usb, Volume2, Wifi } from "lucide-react";
import api from "../../api/axios";

const newInput = (n) => ({ id: crypto.randomUUID(), name: `Input ${n}`, url: "", kind: "live", loop: false, video: true, audio: true, volume: 1, muted: false, denoise: true, speechLevel: true, gainDb: 0, pan: 0, gate: true, compressor: true, deEsser: true, eqLowDb: 0, eqMidDb: 0, eqHighDb: 0, syncMs: 0, splitStereo: false, channel1Name: "Analog 1", channel2Name: "Analog 2", channel1Volume: .8, channel2Volume: .8, channel1GainDb: 0, channel2GainDb: 0, channel1Pan: 0, channel2Pan: 0, channel1Muted: false, channel2Muted: false });
const newDestination = (n) => ({ name: n === 1 ? "YouTube" : `Destination ${n}`, ingestUrl: n === 1 ? "rtmps://a.rtmps.youtube.com:443/live2" : "", streamKey: "", enabled: true });
const initial = { inputs: [{ ...newInput(1), name: "GoPro 1", url: "srt://0.0.0.0:8554?mode=listener&latency=80000", volume: .8, gate: false, deEsser: false }], overlays: [], destinations: [newDestination(1)], quality: "1080p", layout: "single", programInput: 0, record: false, recordingName: "Sunday-Service", audioMix: { mode: "auto", highPass: true, normalize: false, limiter: true, targetLufs: -16, masterGainDb: 0, noiseReduction: 25, autoGain: true, lowLatency: true }, localOutput: { enabled: true, protocol: "srt", host: "0.0.0.0", port: 10000, latencyMs: 80 } };

export default function LiveBroadcastPage() {
  const [studio, setStudio] = useState(() => { try { return JSON.parse(localStorage.getItem("mahima_broadcast_studio")) || initial; } catch { return initial; } });
  const [status, setStatus] = useState({ state: "idle", recentLog: [] });
  const [preview, setPreview] = useState(0);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [devices, setDevices] = useState([]);
  const [devicePermission, setDevicePermission] = useState("prompt");
  const [previewDevice, setPreviewDevice] = useState(null);
  const [youtube, setYoutube] = useState({ configured: false, connected: false });
  const [preflight, setPreflight] = useState(null);
  const localPreviewRef = useRef(null);
  const localStreamRef = useRef(null);
  const active = ["live", "starting"].includes(status.state);
  const refresh = useCallback(async () => { try { setStatus((await api.get("/live-broadcast/status")).data); } catch (e) { setError(message(e, "Could not read studio status.")); } }, []);
  const refreshYoutube = useCallback(async () => { try { setYoutube((await api.get("/live-broadcast/youtube/status")).data); } catch { /* stream-key mode remains available */ } }, []);
  useEffect(() => { refresh(); refreshYoutube(); const timer = setInterval(refresh, 4000); return () => clearInterval(timer); }, [refresh, refreshYoutube]);
  const enumerateDevices = useCallback(async () => {
    if (!navigator.mediaDevices?.enumerateDevices) return setError("Media-device discovery is unavailable in this browser. Use HTTPS or the installed mobile app.");
    try { const list = await navigator.mediaDevices.enumerateDevices(); setDevices(list.filter(d => d.kind === "videoinput" || d.kind === "audioinput")); } catch (e) { setError(`Device discovery failed: ${e.message}`); }
  }, []);
  useEffect(() => { enumerateDevices(); const changed = () => enumerateDevices(); navigator.mediaDevices?.addEventListener?.("devicechange", changed); return () => { navigator.mediaDevices?.removeEventListener?.("devicechange", changed); localStreamRef.current?.getTracks().forEach(t => t.stop()); }; }, [enumerateDevices]);
  const update = (key, value) => setStudio((s) => ({ ...s, [key]: value }));
  const patchInput = (i, patch) => update("inputs", studio.inputs.map((x, n) => n === i ? { ...x, ...patch } : x));
  const patchDestination = (i, patch) => update("destinations", studio.destinations.map((x, n) => n === i ? { ...x, ...patch } : x));
  const program = studio.inputs[studio.programInput];
  const previewInput = studio.inputs[preview];
  const canStart = studio.inputs.some(x => x.url?.trim()) && (studio.destinations.some(x => x.enabled && x.streamKey.trim()) || studio.localOutput?.enabled || studio.record);
  const overlayPreview = useMemo(() => studio.overlays.filter(x => x.value.trim()), [studio.overlays]);

  function savePreset() { localStorage.setItem("mahima_broadcast_studio", JSON.stringify({ ...studio, destinations: studio.destinations.map(d => ({ ...d, streamKey: "" })) })); setError(""); }
  function applyLowLatencySpeechPreset() { setStudio(s => ({ ...s, inputs: s.inputs.map(x => x.audio ? { ...x, volume: .8, gainDb: 0, pan: 0, channel1Volume: .8, channel2Volume: .8, channel1GainDb: 0, channel2GainDb: 0, channel1Pan: 0, channel2Pan: 0, denoise: true, speechLevel: true, gate: false, compressor: true, deEsser: false, eqLowDb: 0, eqMidDb: 1, eqHighDb: 0, syncMs: 0 } : x), audioMix: { ...s.audioMix, mode: "auto", highPass: true, normalize: false, limiter: true, targetLufs: -16, masterGainDb: 0, noiseReduction: 25, autoGain: true, lowLatency: true }, localOutput: { ...s.localOutput, latencyMs: 80 } })); setError("Low-latency speech preset applied. Restart the stream, then calibrate A/V sync with a hand clap."); }
  function addLaptopAudio(device) { const name = device.label || "Laptop audio"; update("inputs", [...studio.inputs, { ...newInput(studio.inputs.length + 1), name, url: `dshow://audio=${name}`, video: false }]); setError("Laptop audio added using Windows DirectShow. This works when the API/FFmpeg runs on this laptop. If your API is hosted elsewhere, replace the DirectShow URL with an RTMP/SRT/UDP feed from a local bridge."); }
  function addMedia() { update("inputs", [...studio.inputs, { ...newInput(studio.inputs.length + 1), name: `Media ${studio.inputs.length + 1}`, kind: "media", loop: true, audio: false, denoise: false, speechLevel: false, gate: false, compressor: false, deEsser: false }]); }
  async function grantAndScan() { try { const permissionStream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true }); permissionStream.getTracks().forEach(t => t.stop()); setDevicePermission("granted"); await enumerateDevices(); } catch (e) { setDevicePermission("denied"); setError(e.name === "NotAllowedError" ? "Camera/microphone permission was denied. Allow it in the browser site settings and scan again." : `Could not open local devices: ${e.message}`); } }
  async function testDevice(device) { try { localStreamRef.current?.getTracks().forEach(t => t.stop()); const constraints = device.kind === "videoinput" ? { video: { deviceId: { exact: device.deviceId } }, audio: false } : { video: false, audio: { deviceId: { exact: device.deviceId } } }; const stream = await navigator.mediaDevices.getUserMedia(constraints); localStreamRef.current = stream; setPreviewDevice(device); if (localPreviewRef.current) { localPreviewRef.current.srcObject = stream; await localPreviewRef.current.play().catch(() => {}); } } catch (e) { setError(`Device test failed: ${e.message}`); } }
  async function shareScreen() { try { localStreamRef.current?.getTracks().forEach(t => t.stop()); const stream = await navigator.mediaDevices.getDisplayMedia({ video: true, audio: true }); localStreamRef.current = stream; setPreviewDevice({ kind: "display", label: "Screen / window share" }); if (localPreviewRef.current) { localPreviewRef.current.srcObject = stream; await localPreviewRef.current.play().catch(() => {}); } stream.getVideoTracks()[0].addEventListener("ended", () => setPreviewDevice(null), { once: true }); } catch (e) { if (e.name !== "NotAllowedError") setError(`Screen capture failed: ${e.message}`); } }
  async function switchProgram(programInput, layout = studio.layout) {
    if (!active) { setStudio(s => ({ ...s, programInput, layout })); return; }
    setBusy(true); setError("");
    try {
      const { data } = await api.post("/live-broadcast/switch", { programInput, layout });
      setStatus(data);
      setStudio(s => ({ ...s, programInput, layout }));
    } catch (e) { setError(message(e, "Live switch could not be completed.")); }
    finally { setBusy(false); }
  }
  function take() { return switchProgram(preview, studio.layout); }
  function chooseLayout(layout) { return switchProgram(studio.programInput, layout); }
  async function start() { setBusy(true); setError(""); try { setStatus((await api.post("/live-broadcast/start", studio)).data); update("destinations", studio.destinations.map(d => ({ ...d, streamKey: "" }))); } catch (e) { setError(message(e, "Broadcast could not be started.")); } finally { setBusy(false); } }
  async function stop() { setBusy(true); try { setStatus((await api.post("/live-broadcast/stop")).data); } catch (e) { setError(message(e, "Broadcast could not be stopped.")); } finally { setBusy(false); } }
  async function connectYoutube() { try { const { data } = await api.post("/live-broadcast/youtube/authorize"); window.location.assign(data.authorizationUrl); } catch (e) { setError(message(e, "YouTube login could not be started.")); } }
  async function disconnectYoutube() { await api.delete("/live-broadcast/youtube/connection"); setYoutube({ ...youtube, connected: false, channelTitle: null }); }
  async function runPreflight() { setBusy(true); setError(""); try { const { data } = await api.get("/live-broadcast/preflight"); setPreflight(data); if (!data.ready) setError(data.error || "FFmpeg broadcast preflight failed."); } catch (e) { setError(message(e, "FFmpeg broadcast preflight failed.")); } finally { setBusy(false); } }
  async function startTestPattern() { setBusy(true); setError(""); try { const request = { inputs: [{ id: "test-bars", name: "OBS test bars", url: "lavfi://testsrc2=size=1280x720:rate=30", video: true, audio: false }, { id: "test-tone", name: "1 kHz test tone", url: "lavfi://sine=frequency=1000:sample_rate=44100", video: false, audio: true, volume: .2, denoise: false }], destinations: [], overlays: [{ type: "text", value: "MAHIMA OBS TEST", position: "lower-third" }], quality: "720p", layout: "single", programInput: 0, record: false, audioMix: { mode: "manual", highPass: false, normalize: false, limiter: true, targetLufs: -16 }, localOutput: { ...(studio.localOutput || initial.localOutput), enabled: true } }; setStatus((await api.post("/live-broadcast/start", request)).data); } catch (e) { setError(message(e, "OBS test pattern could not be started.")); } finally { setBusy(false); } }

  return <main className="min-h-full bg-[#0b1120] p-3 text-slate-100 md:p-5">
    <div className="mx-auto max-w-[1600px] space-y-4">
      <header className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-700 bg-slate-900 px-5 py-4">
        <div><p className="text-xs font-black uppercase tracking-[.25em] text-red-500">Mahima Live Production</p><h1 className="text-2xl font-black">Broadcast Studio</h1></div>
        <div className="flex items-center gap-2"><button onClick={savePreset} className="tool"><Save /> Save preset</button><button onClick={refresh} className="tool"><RefreshCw /> Status</button><span className={`rounded-full px-4 py-2 text-xs font-black ${active ? "animate-pulse bg-red-600" : "bg-slate-700"}`}>{active ? "● ON AIR" : status.state?.toUpperCase()}</span></div>
      </header>
      {error && <div className="flex gap-2 rounded-lg border border-amber-600/50 bg-amber-950/60 p-3 text-sm text-amber-200"><AlertTriangle className="h-5 w-5 shrink-0" />{error}</div>}
      {!error && status.lastError && <div className="flex gap-2 rounded-lg border border-red-600/50 bg-red-950/60 p-3 text-sm text-red-200"><AlertTriangle className="h-5 w-5 shrink-0" /><span><strong>Encoder stopped:</strong> {status.lastError}</span></div>}

      <section className="rounded-xl border border-slate-700 bg-slate-900 p-4">
        <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 font-black"><ScanLine className="h-5 w-5 text-cyan-400" />Local Device Center</h2><p className="mt-1 text-xs text-slate-400">Automatically updates when a USB, camera, capture card, microphone, or OS audio device is connected or removed.</p></div><div className="flex gap-2"><button onClick={grantAndScan} className="tool"><Usb /> Allow & scan</button><button onClick={shareScreen} className="tool"><ScreenShare /> Share screen</button></div></div>
        <div className="grid gap-4 lg:grid-cols-[1fr_360px]">
          <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{devices.map((d, i) => <div key={`${d.kind}-${d.deviceId}`} className={`rounded-lg border p-3 ${previewDevice?.deviceId === d.deviceId ? "border-cyan-400 bg-cyan-950/40" : "border-slate-700 bg-slate-950"}`}><button onClick={() => testDevice(d)} className="flex w-full items-center gap-3 text-left">{d.kind === "videoinput" ? <Camera className="h-5 w-5 text-blue-400" /> : <Mic className="h-5 w-5 text-emerald-400" />}<span className="min-w-0 flex-1"><strong className="block truncate text-sm">{d.label || `${d.kind === "videoinput" ? "Camera" : "Microphone"} ${i + 1}`}</strong><small className="text-slate-500">{d.kind === "videoinput" ? "Video device" : "Audio device"}</small></span></button>{d.kind === "audioinput" && <button disabled={active || studio.inputs.length >= 8} onClick={() => addLaptopAudio(d)} className="mt-2 w-full rounded border border-emerald-700 py-1 text-[11px] font-bold text-emerald-300">Add to mixer</button>}</div>)}{!devices.length && <Empty text={devicePermission === "denied" ? "Permission denied. Update browser site permissions." : "Select Allow & scan to reveal connected device names."} />}</div>
          <div className="relative aspect-video overflow-hidden rounded-lg border border-slate-700 bg-black"><video ref={localPreviewRef} muted playsInline className="h-full w-full object-contain" /><span className="absolute bottom-2 left-2 rounded bg-black/70 px-2 py-1 text-xs">{previewDevice?.label || "Local preview"}</span></div>
        </div>
        <div className="mt-3 flex gap-2 rounded-lg border border-blue-800/60 bg-blue-950/40 p-3 text-xs text-blue-200"><Wifi className="h-4 w-4 shrink-0" /><span><strong>GoPro Wi-Fi:</strong> browsers cannot scan Wi-Fi cameras. Connect the GoPro to the same network and expose its feed through the local bridge/RTMP receiver, then add that RTSP, RTMP, UDP, or HTTP URL under Inputs. Bluetooth supports control or OS-registered audio; its bandwidth is not suitable for GoPro video.</span></div>
      </section>

      <section className="grid gap-4 xl:grid-cols-[1fr_1fr_330px]">
        <Monitor title="PREVIEW" accent="border-emerald-500" input={previewInput} overlays={overlayPreview} layout={studio.layout} />
        <Monitor title="PROGRAM" accent="border-red-500" input={program} overlays={overlayPreview} layout={studio.layout} live={active} />
        <div className="rounded-xl border border-slate-700 bg-slate-900 p-4">
          <h2 className="mb-3 text-sm font-black uppercase tracking-wider text-slate-400">Switcher</h2>
          <div className="grid grid-cols-2 gap-2">{studio.inputs.map((x, i) => x.video && <button key={x.id} onClick={() => setPreview(i)} className={`rounded-lg border p-3 text-left text-sm font-bold ${preview === i ? "border-emerald-400 bg-emerald-950" : "border-slate-700 bg-slate-800"}`}><span className="block text-xs text-slate-400">{i + 1}</span>{x.name}</button>)}</div>
          <button disabled={busy} onClick={take} className="mt-3 w-full rounded-lg bg-gradient-to-r from-emerald-600 to-red-600 py-3 font-black disabled:opacity-50">TAKE → PROGRAM</button>
          <div className="mt-4 grid grid-cols-2 gap-2">{["single", "split", "pip", "grid"].map(x => <button key={x} disabled={busy} onClick={() => chooseLayout(x)} className={`rounded-lg border py-2 text-xs font-bold uppercase ${studio.layout === x ? "border-blue-400 bg-blue-950" : "border-slate-700"}`}>{x}</button>)}</div>
          <p className="mt-3 text-[11px] text-slate-400">Sources remain connected while TAKE and layout commands update the live program.</p>
        </div>
      </section>

      <section className="grid gap-4 xl:grid-cols-[1.3fr_.8fr_.9fr]">
        <Panel title="Inputs & media" icon={Camera} action={<div className="flex gap-2"><button disabled={active || studio.inputs.length >= 8} onClick={addMedia} className="mini"><Film /> Media</button><button disabled={active || studio.inputs.length >= 8} onClick={() => update("inputs", [...studio.inputs, newInput(studio.inputs.length + 1)])} className="mini"><CirclePlus /> Live</button></div>}>
          <div className="space-y-2">{studio.inputs.map((x, i) => <div key={x.id} className="rounded-lg border border-slate-700 bg-slate-950 p-3"><div className="flex gap-2"><select disabled={active} value={x.kind || "live"} onChange={e => patchInput(i, { kind: e.target.value, loop: e.target.value === "media" })} className="field w-24"><option value="live">Live</option><option value="media">Media</option></select><input disabled={active} value={x.name} onChange={e => patchInput(i, { name: e.target.value })} className="field w-32 font-bold" /><input disabled={active} value={x.url} onChange={e => patchInput(i, { url: e.target.value })} placeholder={x.kind === "media" ? "Server file path or HTTP media URL" : "RTSP / RTMP / SRT / UDP / HTTP source"} className="field min-w-0 flex-1 font-mono" /><button disabled={active || studio.inputs.length === 1} onClick={() => update("inputs", studio.inputs.filter((_, n) => n !== i))} className="icon"><Trash2 /></button></div><div className="mt-2 flex flex-wrap items-center gap-3 text-xs"><Toggle label="Video" checked={x.video} set={v => patchInput(i, { video: v })} /><Toggle label="Audio" checked={x.audio} set={v => patchInput(i, { audio: v })} />{x.kind === "media" && <Toggle label="Loop/background" checked={x.loop ?? true} set={v => patchInput(i, { loop: v })} />}<Toggle label="Mute" checked={x.muted} set={v => patchInput(i, { muted: v })} /><Toggle label="Denoise" checked={x.denoise ?? true} set={v => patchInput(i, { denoise: v })} /><Toggle label="Speech" checked={x.speechLevel ?? false} set={v => patchInput(i, { speechLevel: v })} /><Volume2 className="h-4 w-4" /><input type="range" min="0" max="2" step=".05" value={x.volume} onChange={e => patchInput(i, { volume: +e.target.value })} /><span>{Math.round(x.volume * 100)}%</span></div></div>)}</div>
          <div className="mt-3 space-y-2">{studio.inputs.filter(x => x.audio).map(x => { const i = studio.inputs.findIndex(y => y.id === x.id); return <React.Fragment key={x.id}><div className="flex items-center justify-between rounded-lg border border-blue-900 bg-blue-950/40 p-3 text-xs"><span><b>USB interface channel mode</b><small className="ml-2 text-slate-400">Split Left/Right into independent analog channels</small></span><Toggle label="Auto split" checked={x.splitStereo ?? false} set={v => patchInput(i, { splitStereo: v })} /></div>{x.splitStereo && <SplitConsole input={x} patch={p => patchInput(i, p)} disabled={active} />}<ChannelStrip input={x} disabled={active} patch={p => patchInput(i, p)} /></React.Fragment>; })}</div>
          <div className="mt-3 rounded-lg border border-cyan-900 bg-cyan-950/30 p-3 text-xs">
            <div className="mb-2 flex flex-wrap items-center justify-between gap-2"><strong className="flex items-center gap-2"><BrainCircuit className="h-4 w-4 text-cyan-300" />AI adaptive master bus</strong><div className="flex gap-2"><button disabled={active} onClick={applyLowLatencySpeechPreset} className="mini">Optimal speech preset</button><select disabled={active} value={studio.audioMix?.mode || "auto"} onChange={e => update("audioMix", { ...studio.audioMix, mode: e.target.value })} className="field py-1"><option value="auto">AI auto mix</option><option value="manual">Manual mix</option></select></div></div>
            <div className="flex flex-wrap gap-3"><Toggle label="80 Hz rumble cut" checked={studio.audioMix?.highPass ?? true} set={v => update("audioMix", { ...studio.audioMix, highPass: v })} /><Toggle label="Loudness balance" checked={studio.audioMix?.normalize ?? true} set={v => update("audioMix", { ...studio.audioMix, normalize: v })} /><Toggle label="Anti-clip limiter" checked={studio.audioMix?.limiter ?? true} set={v => update("audioMix", { ...studio.audioMix, limiter: v })} /></div>
            <div className="mt-3 flex flex-wrap gap-3"><Toggle label="Adaptive gain" checked={studio.audioMix?.autoGain ?? true} set={v => update("audioMix", { ...studio.audioMix, autoGain: v })} /><Toggle label="Low latency" checked={studio.audioMix?.lowLatency ?? true} set={v => update("audioMix", { ...studio.audioMix, lowLatency: v })} /><Knob label="Noise reduction" value={studio.audioMix?.noiseReduction ?? 35} min={20} max={60} unit=" dB" set={v => update("audioMix", { ...studio.audioMix, noiseReduction: v })} /><Knob label="Target" value={studio.audioMix?.targetLufs ?? -16} min={-24} max={-10} unit=" LUFS" set={v => update("audioMix", { ...studio.audioMix, targetLufs: v })} /><Knob label="Master" value={studio.audioMix?.masterGainDb ?? 0} min={-12} max={12} unit=" dB" set={v => update("audioMix", { ...studio.audioMix, masterGainDb: v })} /></div>
            <p className="mt-3 text-cyan-200">48 kHz processing · adaptive leveling · peak ceiling −1 dBFS. Stop the stream before changing DSP or sync.</p>
          </div>
        </Panel>

        <Panel title="Graphics & overlays" icon={Layers3} action={<button disabled={active || studio.overlays.length >= 8} onClick={() => update("overlays", [...studio.overlays, { type: "text", value: "", position: "lower-third", color: "white", fontSize: 42, opacity: 1 }])} className="mini"><CirclePlus /> Title</button>}>
          <div className="space-y-2">{studio.overlays.map((x, i) => <div key={i} className="rounded-lg bg-slate-950 p-3"><input disabled={active} value={x.value} onChange={e => update("overlays", studio.overlays.map((o, n) => n === i ? { ...o, value: e.target.value } : o))} placeholder="Speaker name, verse, announcement…" className="field w-full" /><div className="mt-2 flex gap-2"><select disabled={active} value={x.position} onChange={e => update("overlays", studio.overlays.map((o, n) => n === i ? { ...o, position: e.target.value } : o))} className="field flex-1"><option value="lower-third">Lower third</option><option value="top-left">Top left</option><option value="top-right">Top right</option><option value="bottom-right">Bottom right</option><option value="center">Center</option></select><button disabled={active} onClick={() => update("overlays", studio.overlays.filter((_, n) => n !== i))} className="icon"><Trash2 /></button></div></div>)}{!studio.overlays.length && <Empty text="Add titles, scripture, speaker names, or announcements." />}</div>
        </Panel>

        <Panel title="Outputs" icon={Radio} action={<button disabled={active || studio.destinations.length >= 4} onClick={() => update("destinations", [...studio.destinations, newDestination(studio.destinations.length + 1)])} className="mini"><CirclePlus /> Destination</button>}>
          <div className="mb-3 rounded-lg border border-red-900/70 bg-red-950/30 p-3 text-xs"><div className="flex items-center justify-between gap-3"><div><strong className="block text-red-200">YouTube Channel</strong><span className="text-slate-400">{youtube.connected ? `Connected: ${youtube.channelTitle || "YouTube channel"}` : youtube.configured ? "Sign in securely with Google OAuth" : "OAuth setup required; stream-key mode is available below"}</span></div>{youtube.connected ? <button onClick={disconnectYoutube} className="mini">Disconnect</button> : <button onClick={connectYoutube} disabled={!youtube.configured} className="mini disabled:opacity-40">Connect</button>}</div></div>
          <div className="space-y-2">{studio.destinations.map((d, i) => <div key={i} className="rounded-lg bg-slate-950 p-3"><div className="flex gap-2"><input disabled={active} value={d.name} onChange={e => patchDestination(i, { name: e.target.value })} className="field w-28" /><input disabled={active} type="password" value={d.streamKey} onChange={e => patchDestination(i, { streamKey: e.target.value })} placeholder="Stream key" className="field min-w-0 flex-1" /></div><input disabled={active} value={d.ingestUrl} onChange={e => patchDestination(i, { ingestUrl: e.target.value })} placeholder="RTMPS ingest URL" className="field mt-2 w-full font-mono" /><div className="mt-2 flex justify-between"><Toggle label="Enabled" checked={d.enabled} set={v => patchDestination(i, { enabled: v })} /><button disabled={active || studio.destinations.length === 1} onClick={() => update("destinations", studio.destinations.filter((_, n) => n !== i))} className="text-xs text-red-400">Remove</button></div></div>)}</div>
          <div className="mt-3 grid grid-cols-2 gap-2"><select disabled={active} value={studio.quality} onChange={e => update("quality", e.target.value)} className="field"><option>1080p</option><option>720p</option><option>480p</option></select><label className="flex items-center gap-2 rounded bg-slate-950 px-3 text-xs"><input disabled={active} type="checkbox" checked={studio.record} onChange={e => update("record", e.target.checked)} /> Record MKV</label></div>
          <div className="mt-3 rounded-lg border border-violet-800/60 bg-violet-950/30 p-3 text-xs"><div className="flex items-center justify-between"><strong className="flex items-center gap-2"><AudioLines className="h-4 w-4" />OBS / vMix program feed</strong><Toggle label="Enabled" checked={studio.localOutput?.enabled ?? false} set={v => update("localOutput", { ...studio.localOutput, enabled: v })} /></div><div className="mt-2 grid grid-cols-[70px_1fr_80px] gap-2"><select disabled={active} value={studio.localOutput?.protocol || "udp"} onChange={e => update("localOutput", { ...studio.localOutput, protocol: e.target.value })} className="field"><option value="udp">UDP</option><option value="srt">SRT</option></select><input disabled={active} value={studio.localOutput?.host || "127.0.0.1"} onChange={e => update("localOutput", { ...studio.localOutput, host: e.target.value })} className="field font-mono" /><input disabled={active} type="number" min="1024" max="65535" value={studio.localOutput?.port || 10000} onChange={e => update("localOutput", { ...studio.localOutput, port: +e.target.value })} className="field" /></div><div className="mt-2"><Knob disabled={active} label="SRT latency" value={studio.localOutput?.latencyMs ?? 80} min={40} max={500} step={10} unit=" ms" set={v => update("localOutput", { ...studio.localOutput, latencyMs: v })} /></div><p className="mt-2 text-violet-200">In OBS add a Media Source: <code>{studio.localOutput?.protocol === "srt" ? `srt://127.0.0.1:${studio.localOutput?.port || 10000}?mode=caller&latency=${(studio.localOutput?.latencyMs ?? 80) * 1000}` : `udp://@127.0.0.1:${studio.localOutput?.port || 10000}`}</code>. This carries mixed audio and program video together.</p><div className="mt-2 flex gap-2"><button disabled={busy || active} onClick={runPreflight} className="mini">FFmpeg preflight</button><button disabled={busy || active} onClick={startTestPattern} className="mini">Send test bars + tone</button></div>{preflight?.ready && <p className="mt-2 text-emerald-300">Ready: {preflight.version}</p>}</div>
        </Panel>
      </section>

      <footer className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-700 bg-slate-900 p-4"><div className="flex items-center gap-4 text-xs text-slate-400"><span><Grid2X2 className="mr-1 inline h-4 w-4" />Up to 8 inputs</span><span><Copy className="mr-1 inline h-4 w-4" />4 outputs</span><span><Mic className="mr-1 inline h-4 w-4" />Audio mix</span></div>{active ? <button disabled={busy} onClick={stop} className="rounded-lg bg-red-600 px-8 py-3 font-black"><Square className="mr-2 inline h-4 w-4" />STOP STREAM</button> : <button disabled={busy || !canStart} onClick={start} className="rounded-lg bg-emerald-600 px-8 py-3 font-black disabled:opacity-40"><Play className="mr-2 inline h-4 w-4" />START STREAM & RECORD</button>}</footer>
      <details className="rounded-xl border border-slate-700 bg-slate-900 p-4"><summary className="cursor-pointer text-sm font-bold">Encoder log</summary><pre className="mt-3 max-h-52 overflow-auto whitespace-pre-wrap rounded bg-black p-3 text-xs text-emerald-400">{status.recentLog?.join("\n") || "Studio ready."}</pre></details>
    </div>
  </main>;
}

function Monitor({ title, accent, input, overlays, live, layout }) { return <div className={`relative aspect-video overflow-hidden rounded-xl border-2 ${accent} bg-black shadow-lg`}><div className="absolute inset-0 grid place-items-center bg-[radial-gradient(circle_at_center,#1e293b,#020617)]"><div className="text-center"><MonitorUp className="mx-auto h-12 w-12 text-slate-600" /><p className="mt-2 font-black">{input?.name || "NO SIGNAL"}</p><p className="text-xs uppercase text-slate-500">{layout} composition</p></div></div><span className="absolute left-3 top-3 rounded bg-black/70 px-2 py-1 text-xs font-black">{title}</span>{live && <span className="absolute right-3 top-3 rounded bg-red-600 px-2 py-1 text-xs font-black">LIVE</span>}{overlays.map((o, i) => <span key={i} className={`absolute rounded bg-black/60 px-4 py-2 font-bold ${positionClass(o.position)}`}>{o.value}</span>)}</div>; }
function Panel({ title, icon: Icon, action, children }) { return <section className="min-w-0 rounded-xl border border-slate-700 bg-slate-900 p-4"><div className="mb-3 flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-black uppercase tracking-wider"><Icon className="h-5 w-5 text-blue-400" />{title}</h2>{action}</div>{children}</section>; }
function Toggle({ label, checked, set }) { return <label className="flex items-center gap-1.5"><input type="checkbox" checked={checked} onChange={e => set(e.target.checked)} />{label}</label>; }
function Knob({ label, value, min, max, step = 1, unit = "", set, disabled }) { return <label className="min-w-[105px] text-[11px] text-slate-300"><span className="mb-1 flex justify-between gap-2"><span>{label}</span><b className="text-white">{value}{unit}</b></span><input disabled={disabled} type="range" min={min} max={max} step={step} value={value} onChange={e => set(+e.target.value)} className="w-full" /></label>; }
function ChannelStrip({ input, patch, disabled }) { return <details className="rounded-lg border border-slate-700 bg-slate-950 p-3"><summary className="cursor-pointer text-xs font-black text-emerald-300">DIGITAL CHANNEL · {input.name}</summary><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Knob disabled={disabled} label="Preamp trim" value={input.gainDb ?? 0} min={-24} max={24} step={.5} unit=" dB" set={v => patch({ gainDb: v })} /><Knob disabled={disabled} label="Pan" value={input.pan ?? 0} min={-1} max={1} step={.1} set={v => patch({ pan: v })} /><Knob disabled={disabled} label="Low 120 Hz" value={input.eqLowDb ?? 0} min={-12} max={12} unit=" dB" set={v => patch({ eqLowDb: v })} /><Knob disabled={disabled} label="Mid 2.5 kHz" value={input.eqMidDb ?? 0} min={-12} max={12} unit=" dB" set={v => patch({ eqMidDb: v })} /><Knob disabled={disabled} label="High 8 kHz" value={input.eqHighDb ?? 0} min={-12} max={12} unit=" dB" set={v => patch({ eqHighDb: v })} /><Knob disabled={disabled} label="A/V sync" value={input.syncMs ?? 0} min={-1000} max={1000} step={10} unit=" ms" set={v => patch({ syncMs: v })} /></div><div className="mt-3 flex flex-wrap gap-3 text-xs"><Toggle label="Noise suppressor" checked={input.denoise ?? true} set={v => patch({ denoise: v })} /><Toggle label="Noise gate" checked={input.gate ?? true} set={v => patch({ gate: v })} /><Toggle label="Compressor" checked={input.compressor ?? true} set={v => patch({ compressor: v })} /><Toggle label="De-esser" checked={input.deEsser ?? true} set={v => patch({ deEsser: v })} /></div><p className="mt-2 text-[11px] text-slate-500">Sync: positive delays audio; negative advances audio relative to video.</p></details>; }
function SplitConsole({ input, patch, disabled }) { return <div className="overflow-x-auto rounded-xl border border-blue-600 bg-gradient-to-b from-[#183b68] to-[#071525] p-4 shadow-2xl"><div className="mb-3 flex items-center justify-between"><strong className="tracking-[.18em] text-blue-100">MAHIMA DIGITAL MIXER</strong><span className="rounded bg-black/40 px-2 py-1 text-[10px] text-cyan-300">USB 2×2 · 48 kHz</span></div><div className="flex min-w-[420px] justify-center gap-4"><MixerFader number="01" name={input.channel1Name || "Analog 1"} volume={input.channel1Volume ?? .8} gain={input.channel1GainDb ?? 0} pan={input.channel1Pan ?? 0} muted={input.channel1Muted ?? false} disabled={disabled} setName={v => patch({ channel1Name: v })} setVolume={v => patch({ channel1Volume: v })} setGain={v => patch({ channel1GainDb: v })} setPan={v => patch({ channel1Pan: v })} setMute={v => patch({ channel1Muted: v })} /><MixerFader number="02" name={input.channel2Name || "Analog 2"} volume={input.channel2Volume ?? .8} gain={input.channel2GainDb ?? 0} pan={input.channel2Pan ?? 0} muted={input.channel2Muted ?? false} disabled={disabled} setName={v => patch({ channel2Name: v })} setVolume={v => patch({ channel2Volume: v })} setGain={v => patch({ channel2GainDb: v })} setPan={v => patch({ channel2Pan: v })} setMute={v => patch({ channel2Muted: v })} /></div></div>; }
function MixerFader({ number, name, volume, gain, pan, muted, disabled, setName, setVolume, setGain, setPan, setMute }) { return <div className={`w-44 rounded-lg border p-3 text-center shadow-xl ${muted ? "border-red-700 bg-red-950/50" : "border-blue-400/40 bg-[#102b4a]"}`}><div className="mb-2 text-[10px] font-black text-cyan-300">CH {number}</div><input disabled={disabled} value={name} onChange={e => setName(e.target.value)} className="field w-full text-center text-xs font-bold" /><div className="mt-3 grid grid-cols-2 gap-2"><Knob disabled={disabled} label="GAIN" value={gain} min={-24} max={24} step={.5} unit=" dB" set={setGain} /><Knob disabled={disabled} label="PAN" value={pan} min={-1} max={1} step={.1} set={setPan} /></div><div className="mt-3 flex h-44 justify-center rounded bg-black/30 p-2"><input disabled={disabled} aria-label={`${name} fader`} type="range" min="0" max="1.25" step=".01" value={volume} onChange={e => setVolume(+e.target.value)} style={{ writingMode: "vertical-lr", direction: "rtl" }} /></div><div className="mt-2 font-mono text-sm font-black text-white">{Math.round(volume * 100)}%</div><button disabled={disabled} onClick={() => setMute(!muted)} className={`mt-2 w-full rounded py-2 text-xs font-black ${muted ? "bg-red-600 text-white" : "bg-slate-700 text-slate-200"}`}>{muted ? "MUTED" : "MUTE"}</button></div>; }
function Empty({ text }) { return <div className="rounded-lg border border-dashed border-slate-700 p-5 text-center text-xs text-slate-500">{text}</div>; }
function message(e, fallback) { return e.response?.data?.message || fallback; }
function positionClass(x) { return x === "top-left" ? "left-5 top-12" : x === "top-right" ? "right-5 top-12" : x === "bottom-right" ? "bottom-5 right-5" : x === "center" ? "left-1/2 top-1/2 -translate-x-1/2" : "bottom-5 left-5"; }
