export function createWorkflowStyles({
  accent = "#2563eb",
  accent2 = "#f59e0b",
  heroFrom = "#123a63",
  heroTo = "#075985",
  kicker = "#bfdbfe",
  title = "#123a63",
  extra = {},
} = {}) {
  const surfaceShadow = "0 18px 44px rgba(15, 23, 42, 0.08)";
  const softBorder = "1px solid rgba(148, 163, 184, 0.22)";

  return {
    page: {
      minHeight: "100%",
      padding: "clamp(14px, 2vw, 24px)",
      borderRadius: 24,
      color: "#172033",
      background:
        `linear-gradient(135deg, ${accent}12 0%, #f8fafc 34%, #fff7ed 100%)`,
    },
    hero: {
      position: "relative",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 20,
      padding: "clamp(20px, 3vw, 30px)",
      borderRadius: 24,
      overflow: "hidden",
      background:
        `linear-gradient(135deg, ${heroFrom} 0%, ${heroTo} 58%, ${accent2} 135%)`,
      color: "#fff",
      boxShadow: "0 24px 60px rgba(15, 23, 42, 0.18)",
      marginBottom: 16,
    },
    kicker: {
      display: "inline-flex",
      alignItems: "center",
      gap: 8,
      marginBottom: 8,
      fontSize: 12,
      fontWeight: 900,
      textTransform: "uppercase",
      color: kicker,
    },
    title: {
      margin: 0,
      fontSize: "clamp(26px, 3vw, 38px)",
      lineHeight: 1.05,
      fontWeight: 950,
    },
    subtitle: {
      margin: "12px 0 0",
      maxWidth: 780,
      color: "rgba(255,255,255,0.82)",
      fontSize: 15,
      lineHeight: 1.65,
    },
    primaryButton: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      minHeight: 44,
      padding: "11px 18px",
      borderRadius: 14,
      border: "1px solid rgba(255,255,255,0.22)",
      background: `linear-gradient(135deg, ${accent}, ${accent2})`,
      color: "#fff",
      fontWeight: 900,
      cursor: "pointer",
      boxShadow: `0 16px 34px ${accent}3d`,
      whiteSpace: "nowrap",
    },
    statsGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(168px, 1fr))",
      gap: 12,
      marginBottom: 16,
    },
    statCard: {
      padding: 16,
      borderRadius: 16,
      background: "rgba(255,255,255,0.94)",
      border: softBorder,
      boxShadow: surfaceShadow,
    },
    statLabel: {
      fontSize: 11,
      color: "#64748b",
      fontWeight: 900,
      textTransform: "uppercase",
    },
    statValue: {
      marginTop: 8,
      fontSize: 30,
      lineHeight: 1,
      fontWeight: 950,
      color: "#0f172a",
    },
    statHint: {
      marginTop: 6,
      fontSize: 12,
      color: "#64748b",
    },
    panel: {
      background: "rgba(255,255,255,0.96)",
      borderRadius: 20,
      padding: 16,
      border: softBorder,
      boxShadow: surfaceShadow,
    },
    tabs: {
      display: "flex",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 14,
    },
    tab: {
      minHeight: 38,
      padding: "8px 13px",
      borderRadius: 12,
      border: "1px solid #e2e8f0",
      cursor: "pointer",
      fontSize: 13,
      fontWeight: 850,
    },
    tableWrap: {
      overflowX: "auto",
      borderRadius: 16,
      border: "1px solid #e2e8f0",
      background: "#fff",
    },
    table: {
      width: "100%",
      borderCollapse: "separate",
      borderSpacing: 0,
      minWidth: 980,
      fontSize: 13,
    },
    th: {
      position: "sticky",
      top: 0,
      zIndex: 1,
      padding: "13px 14px",
      background: "#f8fafc",
      color: "#475569",
      textAlign: "left",
      fontSize: 11,
      textTransform: "uppercase",
      borderBottom: "1px solid #e2e8f0",
    },
    tr: {
      borderBottom: "1px solid #f1f5f9",
    },
    td: {
      padding: 14,
      verticalAlign: "top",
      color: "#1e293b",
      borderBottom: "1px solid #f1f5f9",
    },
    name: {
      fontWeight: 900,
      color: "#0f172a",
    },
    nameSmall: {
      fontWeight: 850,
      color: "#1e293b",
    },
    muted: {
      marginTop: 4,
      color: "#64748b",
      fontSize: 12,
      maxWidth: 320,
      whiteSpace: "normal",
    },
    badge: {
      display: "inline-flex",
      alignItems: "center",
      padding: "5px 10px",
      borderRadius: 999,
      fontSize: 12,
      fontWeight: 900,
      whiteSpace: "nowrap",
    },
    flagGroup: {
      display: "flex",
      flexWrap: "wrap",
      gap: 6,
    },
    flag: {
      display: "inline-flex",
      padding: "5px 9px",
      borderRadius: 999,
      fontSize: 11,
      fontWeight: 900,
      whiteSpace: "nowrap",
    },
    token: {
      display: "inline-flex",
      maxWidth: 170,
      overflow: "hidden",
      borderRadius: 8,
      background: "#f8fafc",
      padding: "3px 7px",
      color: title,
      fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
      fontSize: 12,
      fontWeight: 900,
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    actionGroup: {
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "flex-end",
      gap: 8,
    },
    actionButton: (tone) => ({
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      minHeight: 32,
      padding: "7px 11px",
      borderRadius: 10,
      background: tone,
      color: "#fff",
      border: "none",
      fontSize: 12,
      fontWeight: 900,
      cursor: "pointer",
      whiteSpace: "nowrap",
    }),
    pdfButton: {
      display: "inline-flex",
      alignItems: "center",
      minHeight: 32,
      padding: "7px 11px",
      borderRadius: 10,
      border: "1px solid #cbd5e1",
      background: "#fff",
      color: "#334155",
      fontSize: 12,
      fontWeight: 900,
      textDecoration: "none",
      whiteSpace: "nowrap",
    },
    empty: {
      padding: 30,
      textAlign: "center",
      color: "#64748b",
    },
    emptyCell: {
      padding: 28,
      textAlign: "center",
      color: "#64748b",
    },
    error: {
      marginBottom: 14,
      padding: 14,
      borderRadius: 14,
      background: "#fef2f2",
      border: "1px solid #fecaca",
      color: "#991b1b",
      fontWeight: 850,
    },
    formCard: {
      marginBottom: 16,
      padding: 20,
      borderRadius: 20,
      background: "rgba(255,255,255,0.96)",
      border: softBorder,
      boxShadow: surfaceShadow,
    },
    formHeader: {
      marginBottom: 16,
    },
    formTitle: {
      margin: 0,
      fontSize: 21,
      fontWeight: 950,
      color: title,
    },
    formSub: {
      margin: "6px 0 0",
      color: "#64748b",
      fontSize: 14,
    },
    formGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(230px, 1fr))",
      gap: 14,
    },
    field: {
      display: "block",
    },
    label: {
      display: "block",
      marginBottom: 6,
      fontSize: 11,
      fontWeight: 900,
      color: "#475569",
      textTransform: "uppercase",
    },
    input: {
      width: "100%",
      boxSizing: "border-box",
      border: "1px solid #cbd5e1",
      borderRadius: 12,
      background: "#fff",
      padding: "11px 12px",
      color: "#0f172a",
      fontSize: 14,
      outline: "none",
    },
    textarea: {
      width: "100%",
      boxSizing: "border-box",
      border: "1px solid #cbd5e1",
      borderRadius: 12,
      background: "#fff",
      padding: "11px 12px",
      color: "#0f172a",
      fontSize: 14,
      outline: "none",
      resize: "vertical",
    },
    checkboxLine: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      color: "#334155",
      fontSize: 14,
      fontWeight: 750,
    },
    formActions: {
      gridColumn: "1 / -1",
      display: "flex",
      justifyContent: "flex-end",
      flexWrap: "wrap",
      gap: 10,
      marginTop: 8,
    },
    secondaryButton: {
      minHeight: 40,
      padding: "9px 15px",
      borderRadius: 12,
      border: "1px solid #cbd5e1",
      background: "#fff",
      color: "#334155",
      fontWeight: 850,
      cursor: "pointer",
    },
    darkButton: {
      minHeight: 40,
      padding: "9px 17px",
      borderRadius: 12,
      border: "none",
      background: title,
      color: "#fff",
      fontWeight: 900,
      cursor: "pointer",
    },
    overlay: {
      position: "fixed",
      inset: 0,
      zIndex: 100,
      background: "rgba(15, 23, 42, 0.62)",
      display: "grid",
      placeItems: "center",
      padding: 16,
      backdropFilter: "blur(6px)",
    },
    modalLarge: {
      width: "min(920px, 96vw)",
      maxHeight: "90vh",
      overflowY: "auto",
      background: "#fff",
      borderRadius: 20,
      padding: 22,
      boxShadow: "0 30px 80px rgba(0,0,0,0.35)",
    },
    modalSmall: {
      width: "min(560px, 94vw)",
      maxHeight: "90vh",
      overflowY: "auto",
      background: "#fff",
      borderRadius: 20,
      padding: 22,
      boxShadow: "0 30px 80px rgba(0,0,0,0.35)",
    },
    modalHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
      marginBottom: 18,
    },
    modalTitle: {
      margin: 0,
      fontSize: 21,
      color: title,
      fontWeight: 950,
    },
    closeButton: {
      width: 36,
      height: 36,
      borderRadius: 12,
      border: "none",
      background: "#f1f5f9",
      cursor: "pointer",
      fontWeight: 900,
      color: "#475569",
    },
    personBlock: {
      display: "grid",
      gap: 4,
      padding: 14,
      borderRadius: 14,
      background: "#f8fafc",
      color: "#334155",
      marginBottom: 14,
    },
    modalActions: {
      gridColumn: "1 / -1",
      display: "flex",
      justifyContent: "flex-end",
      flexWrap: "wrap",
      gap: 10,
      marginTop: 8,
    },
    progressRail: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
      gap: 10,
      marginBottom: 16,
    },
    progressStep: {
      display: "flex",
      alignItems: "center",
      gap: 10,
      padding: 12,
      borderRadius: 14,
      background: "rgba(255,255,255,0.88)",
      border: softBorder,
    },
    progressDot: (tone) => ({
      width: 10,
      height: 10,
      borderRadius: 999,
      background: tone,
      boxShadow: `0 0 0 4px ${tone}20`,
      flex: "0 0 auto",
    }),
    progressLabel: {
      display: "block",
      fontSize: 12,
      fontWeight: 900,
      color: "#0f172a",
    },
    progressHint: {
      display: "block",
      marginTop: 2,
      fontSize: 12,
      color: "#64748b",
    },
    ...extra,
  };
}
