BEGIN;

CREATE TABLE IF NOT EXISTS public.accounting_data_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by varchar(250) NOT NULL,
    source_name varchar(500) NOT NULL,
    import_mode varchar(30) NOT NULL,
    before_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    changes jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_accounting_data_snapshots_version
    ON public.accounting_data_snapshots(version);
CREATE INDEX IF NOT EXISTS ix_accounting_data_snapshots_created_at
    ON public.accounting_data_snapshots(created_at DESC);

COMMIT;
