CREATE TABLE IF NOT EXISTS public."AuditLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ActorId" uuid NULL,
    "Action" text NOT NULL,
    "EntityType" text NULL,
    "EntityId" text NULL,
    "Details" text NULL,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_auditlogs_createdat
    ON public."AuditLogs" ("CreatedAt" DESC);

CREATE INDEX IF NOT EXISTS ix_auditlogs_actorid_createdat
    ON public."AuditLogs" ("ActorId", "CreatedAt" DESC);

CREATE INDEX IF NOT EXISTS ix_auditlogs_entity
    ON public."AuditLogs" ("EntityType", "EntityId");

CREATE INDEX IF NOT EXISTS ix_auditlogs_action_createdat
    ON public."AuditLogs" ("Action", "CreatedAt" DESC);
